const fs = require('fs');
const wf = JSON.parse(fs.readFileSync('brain2_current.json', 'utf8'));

const extractCode = [
  "let state;",
  "try { state = JSON.parse($input.first().json.stateRaw || '{}'); } catch (e) { state = {}; }",
  "state.history = state.history || [];",
  "state.major = state.major || null; // RN, PN, HR, Engineering, EdAdminMaster, GradDip",
  "state.degree = state.degree || null;",
  "state.grade = state.grade || null;",
  "state.track = state.track || null;",
  "state.age = state.age || null;",
  "state.weight = state.weight || null;",
  "state.height = state.height || null;",
  "state.govOrPrivate = state.govOrPrivate || null;",
  "state.pnTrack = state.pnTrack || null; // ปกติ, พิเศษ",
  "state.engineeringType = state.engineeringType || null; // เครื่องกล, ความปลอดภัย, 2ปริญญา",
  "state.isSpobTeacher = state.isSpobTeacher ?? null; // ป.บัณฑิต: เป็นครูเครือ สพฐ. หรือไม่",
  "state.conversationEnded = state.conversationEnded || false;",
  "state.detailGiven = state.detailGiven || false;",
  "state.wantsAdmin = false;",
  "",
  "const webhookBody = $('Webhook').first().json.body;",
  "const userId = webhookBody.userId;",
  "const channel = webhookBody.channel || 'general'; // 'general' หรือ 'nursing' ส่งมาจาก server.js",
  "const persona = channel === 'nursing' ? 'อาจารย์' : 'แอดมิน';",
  "const rawMessage = webhookBody.message || '';",
  "state.history.push({ role: 'user', content: rawMessage });",
  "",
  "const text = rawMessage.toLowerCase();",
  "const numbers = (rawMessage.match(/\\d+(\\.\\d+)?/g) || []).map(Number);",
  "const decimalNumbers = (rawMessage.match(/\\d\\.\\d+/g) || []).map(Number); // เก็บไว้แยกต่างหาก กันเคสเกรด 3.0 ถูกตัดทศนิยมจนตรวจไม่เจอ",
  "",
  "// ----- กฎช่องทาง: ห้ามพูดพยาบาลในเพจทั่วไป / ห้ามพูดสาขาอื่นในเพจพยาบาล -----",
  "const channelBlocked = (channel === 'general' && (text.includes('พยาบาล')))",
  "  || (channel === 'nursing' && state.major && !['RN','PN'].includes(state.major));",
  "",
  "// ----- ตรวจคำตอบรับสั้นๆ หลังจากให้รายละเอียดคอร์สไปแล้ว -----",
  "const confirmWords = ['สนใจ', 'ใสใจ', 'สนจ', 'ใช่', 'ตกลง', 'โอเค', 'เอาเลย', 'ครับสนใจ', 'อยากสมัคร', 'สมัคร'];",
  "if (state.detailGiven && !state.conversationEnded && confirmWords.some(w => text.includes(w))) {",
  "  state.wantsAdmin = true;",
  "}",
  "",
  "// ----- ดึงสาขาที่สนใจ (deterministic) -----",
  "if (!state.major && !channelBlocked) {",
  "  if (channel === 'nursing' || text.includes('พยาบาล')) {",
  "    if (text.includes('ผู้ช่วย') || /\\bpn\\b/.test(text)) state.major = 'PN';",
  "    else if (/\\brn\\b/.test(text) || text.includes('พยาบาลศาสตร์')) state.major = 'RN';",
  "    // ถ้าพิมพ์ \"พยาบาล\" ลอยๆ ไม่ระบุ ให้รอถามก่อน (major ยังเป็น null)",
  "  } else if (text.includes('ทรัพยากรมนุษย์') || /\\bhr\\b/.test(text)) {",
  "    state.major = 'HR';",
  "  } else if (text.includes('วิศว') || text.includes('เครื่องกล') || text.includes('ความปลอดภัย') || /2\\s*ปริญญา|สองปริญญา/.test(text)) {",
  "    state.major = 'Engineering';",
  "  } else if (text.includes('บริหารการศึกษา') || text.includes('ป.โท')) {",
  "    state.major = 'EdAdminMaster';",
  "  } else if (text.includes('ป.บัณฑิต') || text.includes('บัณฑิตวิชาชีพครู')) {",
  "    state.major = 'GradDip';",
  "  }",
  "}",
  "",
  "// ----- ดึงวุฒิการศึกษา -----",
  "if (!state.degree) {",
  "  if (/กศน/.test(text)) state.degree = 'กศน.';",
  "  else if (/ม\\.?6|มัธยมศึกษาปีที่\\s*6|มัธยมปลาย/.test(text)) state.degree = 'ม.6';",
  "  else if (/ปวช/.test(text)) state.degree = 'ปวช.';",
  "  else if (/ปวส/.test(text)) state.degree = 'ปวส.';",
  "  else if (/ป\\.?ตรี|ปริญญาตรี|bachelor/.test(text)) state.degree = 'ปริญญาตรี';",
  "}",
  "if (!state.job && /ทำงาน|รับราชการ|พนักงาน|ธุรกิจส่วนตัว|อาชีพ|ครู/.test(text)) state.job = rawMessage;",
  "if (!state.experience && /ปี|ปีแล้ว|ประสบการณ์/.test(text)) state.experience = rawMessage;",
  "",
  "// ----- เฉพาะ RN: เกรด/สาย/อายุ/น้ำหนัก/ส่วนสูง -----",
  "if (state.major === 'RN') {",
  "  if (!state.track) {",
  "    if (/วิทย์|วิทยาศาสตร์/.test(text)) state.track = 'วิทย์-คณิต';",
  "    else if (/สังคม|ศิลป์|ภาษา|ศิลภาษา/.test(text)) state.track = 'สายอื่นๆ';",
  "  }",
  "  if (state.grade === null) {",
  "    const g = decimalNumbers.find(n => n >= 0 && n <= 4);",
  "    if (g !== undefined) state.grade = g;",
  "  }",
  "  if (state.age === null) {",
  "    const a = numbers.find(n => n >= 10 && n <= 60 && Number.isInteger(n));",
  "    if (a !== undefined) state.age = a;",
  "  }",
  "  if (state.weight === null) {",
  "    const w = numbers.find(n => n >= 30 && n <= 150);",
  "    if (w !== undefined) state.weight = w;",
  "  }",
  "  if (state.height === null) {",
  "    const h = numbers.find(n => n >= 140 && n <= 210);",
  "    if (h !== undefined) state.height = h;",
  "  }",
  "  // กศน. ไม่รับสำหรับพยาบาล RN ไม่ว่ากรณีใด",
  "  if (state.degree === 'กศน.') state.conversationEnded = true;",
  "}",
  "",
  "// ----- เฉพาะ PN: เลือกภาคปกติ/พิเศษ -----",
  "if (state.major === 'PN' && !state.pnTrack) {",
  "  if (/พิเศษ|เสาร์|อาทิตย์/.test(text)) state.pnTrack = 'พิเศษ';",
  "  else if (/ปกติ|จันทร์|ศุกร์/.test(text)) state.pnTrack = 'ปกติ';",
  "}",
  "",
  "// ----- เฉพาะ Engineering: เลือกหลักสูตร (เครื่องกล/ความปลอดภัย/2ปริญญา) -----",
  "if (state.major === 'Engineering' && !state.engineeringType) {",
  "  const hasMech = /เครื่องกล/.test(text);",
  "  const hasSafety = /ความปลอดภัย/.test(text);",
  "  if (hasMech && hasSafety) state.engineeringType = '2ปริญญา';",
  "  else if (/2\\s*ปริญญา|สองปริญญา/.test(text)) state.engineeringType = '2ปริญญา';",
  "  else if (hasMech) state.engineeringType = 'เครื่องกล';",
  "  else if (hasSafety) state.engineeringType = 'ความปลอดภัย';",
  "}",
  "",
  "// ----- เฉพาะ HR: ที่ทำงานรัฐ/เอกชน -----",
  "if (state.major === 'HR' && !state.govOrPrivate) {",
  "  if (/รัฐ|ราชการ|รัฐวิสาหกิจ/.test(text)) state.govOrPrivate = 'รัฐ';",
  "  else if (/เอกชน|บริษัท/.test(text)) state.govOrPrivate = 'เอกชน';",
  "}",
  "",
  "// ----- เฉพาะ GradDip: เป็นครูเครือ สพฐ. หรือไม่ -----",
  "if (state.major === 'GradDip' && state.isSpobTeacher === null) {",
  "  if (/ไม่ใช่|ไม่ได้เป็น|ไม่มี/.test(text)) state.isSpobTeacher = false;",
  "  else if (/เป็นครู|ใช่|สพฐ/.test(text)) state.isSpobTeacher = true;",
  "}",
  "if (state.major === 'GradDip' && state.isSpobTeacher === false) state.conversationEnded = true;",
  "",
  "// ----- เช็คว่าข้อมูลครบหรือยังตาม major -----",
  "function infoCompleteFor(major) {",
  "  if (major === 'RN') return state.degree && state.grade !== null && state.track && state.age !== null && state.weight !== null && state.height !== null;",
  "  if (major === 'PN') return !!(state.degree && state.pnTrack);",
  "  if (major === 'HR') return state.degree && state.govOrPrivate;",
  "  if (major === 'Engineering') return !!(state.degree && state.engineeringType);",
  "  if (major === 'EdAdminMaster') return !!state.degree;",
  "  if (major === 'GradDip') return state.isSpobTeacher !== null;",
  "  return false;",
  "}",
  "const infoComplete = state.major ? infoCompleteFor(state.major) : false;",
  "",
  "// ----- ถ้าครบแล้วและเป็น RN ให้คำนวณเกณฑ์แบบ deterministic -----",
  "let rnEligible = null;",
  "let rnFailReasons = [];",
  "if (state.major === 'RN' && infoComplete && !state.conversationEnded) {",
  "  const heightM = state.height / 100;",
  "  const bmi = state.weight / (heightM * heightM);",
  "  const gradeMin = state.track === 'วิทย์-คณิต' ? 2.00 : 2.50;",
  "  if (!(bmi >= 17.5 && bmi <= 30)) rnFailReasons.push('BMI');",
  "  if (!(state.height >= 150)) rnFailReasons.push('ส่วนสูง');",
  "  if (!(state.weight >= 40)) rnFailReasons.push('น้ำหนัก');",
  "  if (!(state.age >= 16 && state.age <= 30)) rnFailReasons.push('อายุ');",
  "  if (!(state.grade >= gradeMin)) rnFailReasons.push('เกรดเฉลี่ย');",
  "  rnEligible = rnFailReasons.length === 0;",
  "}",
  "",
  "if (infoComplete) state.detailGiven = true;",
  "",
  "return [{",
  "  json: {",
  "    ...state,",
  "    userId,",
  "    channel,",
  "    persona,",
  "    channelBlocked,",
  "    infoComplete,",
  "    rnEligible,",
  "    rnFailReasons",
  "  }",
  "}];"
].join('\n');

const extractNode = wf.nodes.find(n => n.name === 'Extract Info (Deterministic)');
extractNode.parameters.jsCode = extractCode;

const promptParts = [
  "'คุณคือ \"' + $json.persona + '\" เจ้าหน้าที่ฝ่ายรับสมัคร มหาวิทยาลัยชินวัตร เรียกลูกค้าว่า \"นักศึกษา\" เสมอ (ห้ามใช้คำว่า ท่าน หรือ คุณ) พูดสุภาพ ลงท้ายด้วยค่ะ/นะคะเสมอ ห้ามใช้ครับ ตอบกระชับเป็นธรรมชาติ ห้ามพิมพ์ตัวเลข/ราคาที่ไม่ได้ให้มาในข้อมูลนี้เอง ห้ามมั่วข้อมูล. ข้อมูลที่ต้องใช้ตอบ (ห้ามมั่ว ใช้ตามนี้เท่านั้น): ' + (function(){ ",
  "const j = $json; let facts = ''; ",
  "const FORM_NURSING = 'https://forms.gle/MKg5NfUtvjj1xr2k7'; ",
  "const FORM_ENGINEERING = 'https://forms.gle/nPJuM28hHuynxtp97'; ",
  "const FORM_HR = 'https://forms.gle/YBXny8GdW1VAXocJ6'; ",
  "const FORM_EDU = 'https://docs.google.com/forms/d/17Tq151nb8UH2C5QyL1EF922PzHrpGA_bCJhd7tnToLQ/viewform'; ",
  "if (j.channelBlocked) { facts = 'ลูกค้าถามเรื่องที่ช่องทางนี้ตอบไม่ได้ (เพจทั่วไปห้ามพูดพยาบาล หรือเพจพยาบาลห้ามพูดสาขาอื่น) ให้แนะนำไปเพจที่ถูกต้องอย่างสุภาพสั้นๆ ห้ามถามข้อมูลอะไรต่อ'; } ",
  "else if (j.major === 'RN' && j.degree === 'กศน.' && j.conversationEnded) { facts = 'ลูกค้าใช้วุฒิ กศน. สมัคร RN ซึ่งหลักสูตรพยาบาลยังไม่รับวุฒิเทียบเท่า ให้ตอบสุภาพว่า \"หลักสูตรพยาบาลยังไม่รับวุฒิเทียบเท่าต้องขออภัยด้วยนะคะ\"'; } ",
  "else if (j.major === 'GradDip' && j.conversationEnded) { facts = 'ลูกค้าไม่ได้เป็นครูในโรงเรียนเครือ สพฐ. ซึ่งเป็นเงื่อนไขจำเป็นของหลักสูตร ป.บัณฑิต ให้แจ้งสุภาพว่าหลักสูตรนี้รับเฉพาะครูที่มีเอกสารรับรองการทำงานในโรงเรียนเครือ สพฐ. เท่านั้น ขออภัยในความไม่สะดวก'; } ",
  "else if (j.wantsAdmin) { ",
  "  if (['RN','PN'].includes(j.major)) { facts = 'ลูกค้าสนใจสมัคร ' + j.major + ' แล้ว ให้ตอบรับสั้นๆ แล้วส่งลิงก์แบบฟอร์มสมัครเรียนคณะพยาบาลศาสตร์นี้ให้: ' + FORM_NURSING + ' พร้อมแจ้งว่าหลังสมัครแล้วให้ส่งสลิปโอนเงินค่าสมัครและเอกสาร (บัตรประชาชน, วุฒิการศึกษา, รูปถ่ายหน้าตรง) ทางแชทนี้ได้เลย'; } ",
  "  else if (j.major === 'Engineering') { facts = 'ลูกค้าสนใจสมัครวิศวกรรมศาสตร์แล้ว ให้ตอบรับสั้นๆ แล้วส่งลิงก์แบบฟอร์มสมัครคณะวิศวกรรมศาสตร์นี้ให้: ' + FORM_ENGINEERING; } ",
  "  else if (j.major === 'HR') { facts = 'ลูกค้าสนใจสมัคร HR แล้ว ให้ตอบรับสั้นๆ แล้วส่งลิงก์แบบฟอร์มสมัครคณะการจัดการนี้ให้: ' + FORM_HR; } ",
  "  else if (['EdAdminMaster','GradDip'].includes(j.major)) { facts = 'ลูกค้าสนใจสมัคร ' + j.major + ' แล้ว ให้ตอบรับสั้นๆ แล้วส่งลิงก์แบบฟอร์มสมัครปริญญาโทบริหารการศึกษา/ป.บัณฑิตนี้ให้: ' + FORM_EDU; } ",
  "  else { facts = 'ลูกค้าตอบรับสนใจสมัครแล้วหลังจากได้รับรายละเอียดคอร์ส ให้ตอบรับสั้นๆ ว่าจะให้เจ้าหน้าที่ติดต่อนัดหมายต่อ แจ้งเบอร์ 082-383-0243 และ Line: @siu.admission'; } ",
  "} ",
  "else if (!j.major) { facts = 'ยังไม่ทราบว่าลูกค้าสนใจสาขาไหน ให้ทักทายสุภาพแล้วถามว่าสนใจหลักสูตรไหนคะ (เลือกได้: พยาบาลศาสตร์ RN, ผู้ช่วยพยาบาล PN, ทรัพยากรมนุษย์ HR, วิศวกรรมศาสตร์, ป.โทบริหารการศึกษา, ป.บัณฑิตวิชาชีพครู) ห้ามพูดถึงพยาบาลถ้าเป็นเพจทั่วไป'; } ",
  "else if (!j.infoComplete) { ",
  "  if (j.major === 'RN') { facts = 'สาขาที่ลูกค้าสนใจ: RN (พยาบาลศาสตร์). ข้อมูลที่มีแล้ว (ห้ามถามซ้ำ): วุฒิ=' + (j.degree||'-') + ' เกรด=' + (j.grade??'-') + ' สาย=' + (j.track||'-') + ' อายุ=' + (j.age??'-') + ' น้ำหนัก=' + (j.weight??'-') + ' ส่วนสูง=' + (j.height??'-') + '. ให้ถามเฉพาะข้อมูลที่ยังขาดจากรายการนี้เท่านั้น: วุฒิการศึกษา, เกรดเฉลี่ย, สายการเรียน, อายุ, น้ำหนัก(กก.), ส่วนสูง(ซม.)'; } ",
  "  else if (j.major === 'PN') { facts = 'สาขาที่ลูกค้าสนใจ: PN (ผู้ช่วยพยาบาล). ข้อมูลที่มีแล้ว (ห้ามถามซ้ำ): วุฒิ=' + (j.degree||'-') + ' ภาคเรียน=' + (j.pnTrack||'-') + '. ให้ถามเฉพาะข้อมูลที่ยังขาด: วุฒิการศึกษา, และต้องการเรียนภาคปกติ(จันทร์-ศุกร์ ที่ปทุมธานี) หรือภาคพิเศษ(เสาร์-อาทิตย์ ที่อโศก)'; } ",
  "  else if (j.major === 'Engineering') { facts = 'สาขาที่ลูกค้าสนใจ: วิศวกรรมศาสตร์. ข้อมูลที่มีแล้ว (ห้ามถามซ้ำ): วุฒิ=' + (j.degree||'-') + ' หลักสูตร=' + (j.engineeringType||'-') + '. ให้ถามเฉพาะข้อมูลที่ยังขาด: วุฒิการศึกษา, และสนใจหลักสูตรเครื่องกล, ความปลอดภัย, หรือหลักสูตร 2 ปริญญา (เรียนทั้งเครื่องกล+ความปลอดภัยพร้อมกัน)'; } ",
  "  else if (j.major === 'GradDip') { facts = 'สาขาที่ลูกค้าสนใจ: ป.บัณฑิตวิชาชีพครู ให้ถามว่าเป็นครูในโรงเรียนเครือ สพฐ. ที่มีเอกสารรับรองการทำงานในตำแหน่งครูผู้สอนหรือไม่ (เป็นเงื่อนไขจำเป็น)'; } ",
  "  else if (j.major === 'HR') { facts = 'สาขาที่ลูกค้าสนใจ: HR (ทรัพยากรมนุษย์). ข้อมูลที่มีแล้ว (ห้ามถามซ้ำ): วุฒิ=' + (j.degree||'-') + ' หน่วยงาน=' + (j.govOrPrivate||'-') + '. ให้ถามเฉพาะข้อมูลที่ยังขาด: วุฒิการศึกษา และปัจจุบันทำงานหน่วยงานรัฐหรือเอกชน'; } ",
  "  else { facts = 'สาขาที่ลูกค้าสนใจ: ป.โทบริหารการศึกษา. ข้อมูลที่มีแล้ว (ห้ามถามซ้ำ): วุฒิ=' + (j.degree||'-') + '. ให้ถามวุฒิการศึกษา (ต้องมีใบประกอบวิชาชีพครู)'; } ",
  "} ",
  "else if (j.major === 'RN') { ",
  "  facts = j.rnEligible ",
  "    ? 'ลูกค้าผ่านเกณฑ์คุณสมบัติเบื้องต้นสำหรับ RN (คุณสมบัติคือจบ ม.6 สายสามัญ (ไม่รับ กศน.), พยาบาลศาสตร์ 4 ปี, ค่าเทอมตลอดหลักสูตร 700,000 บาท, ค่าสมัคร 1,000 บาท, กู้ กยศ.ได้ปีละประมาณ 90,000 บาท แต่การอนุมัติขึ้นกับ กยศ. เท่านั้น มหาวิทยาลัยแจ้งผลแทนไม่ได้, พักหอในได้ เทอมละ 4,000 บาท, รับรองจากสภาการพยาบาล, ตอนนี้เหลือโควต้าไม่เกิน 3 ที่นั่งสุดท้าย) ให้แจ้งว่าผ่านเกณฑ์เบื้องต้นค่ะ พร้อมแจ้งโควต้าที่เหลือน้อย กระตุ้นให้รีบสมัคร แล้วถามว่าสนใจสมัครเลยไหมคะ' ",
  "    : 'ลูกค้าไม่ผ่านเกณฑ์ RN เนื่องจาก: ' + j.rnFailReasons.join(', ') + ' ให้แจ้งสุภาพว่าไม่ผ่านเกณฑ์ข้อไหน และแนะนำพิจารณาหลักสูตรผู้ช่วยพยาบาล (PN) แทน'; ",
  "} ",
  "else if (j.major === 'PN') { ",
  "  const locationLine = j.pnTrack === 'พิเศษ' ? 'เรียนที่อาคาร OAI ย่านอโศก กรุงเทพมหานคร (เข้าแลบ/ฝึกงานต้องไปปทุมธานี)' : 'เรียนที่มหาวิทยาลัยชินวัตร จังหวัดปทุมธานี'; ",
  "  facts = 'PN (ผู้ช่วยพยาบาล 1 ปี ภาค' + j.pnTrack + ' ' + locationLine + ') ค่าสมัคร 500 บาท ภาคเรียนที่ 1 มีค่าใช้จ่ายส่วนต่าง 31,000 บาท (รวมค่าสมัครแล้ว) แบ่งชำระได้ ภาคเรียนที่ 2-3 สำรองชำระล่วงหน้า 50,000 บาท กู้ กยศ.ได้สูงสุด 50,000 บาทตลอดหลักสูตร (อนุมัติตามเงื่อนไข กยศ.) เกณฑ์ทั่วไป: อายุ 16-60 ปี, ส่วนสูง 150ซม.ขึ้นไป, น้ำหนัก 40กก.ขึ้นไป, BMI ประมาณ 17.5-30 แต่เกณฑ์ BMI ยืดหยุ่นพูดคุยกันได้ ไม่ใช่เกณฑ์ตัดสิทธิ์เด็ดขาด ให้สรุปข้อมูลคอร์สแล้วถามว่าสนใจสมัครเลยไหมคะ'; ",
  "} ",
  "else if (j.major === 'HR') { ",
  "  const fee = j.govOrPrivate === 'รัฐ' ? '18,750 บาท/เทอม (มี 2 ทุนรวมกัน: ทุนลด 5,000 บาท และทุนลด 25% จากปกติ 30,000 บาท)' : '25,000 บาท/เทอม (มีทุนส่วนลด 5,000 บาท จากปกติ 30,000 บาท)'; ",
  "  facts = 'HRM การจัดการทรัพยากรมนุษย์ (เรียนออนไลน์วันอาทิตย์ Block course, เทียบโอนได้ สายบริหารธุรกิจเหลือเรียนประมาณ 1.5 ปี) ลูกค้าทำงาน ' + j.govOrPrivate + ' ค่าเทอม ' + fee + ' ผ่อนชำระรายเดือนได้ ให้สรุปแล้วถามว่าสนใจสมัครเลยไหมคะ'; ",
  "} ",
  "else if (j.major === 'Engineering') { ",
  "  const isTransfer = ['ปวส.','ปริญญาตรี'].includes(j.degree); ",
  "  let detail = ''; ",
  "  if (j.engineeringType === 'เครื่องกล') detail = isTransfer ? 'เทียบโอนเหลือเรียน 2 ปี ค่าเทอมเหมา 150,000 บาท' : 'เรียนเต็ม 4 ปี ค่าเทอม 280,000 บาท'; ",
  "  else if (j.engineeringType === 'ความปลอดภัย') detail = isTransfer ? 'เทียบโอนเหลือเรียน 2 ปี ค่าเทอมเหมา 150,000 บาท' : 'เรียนเต็ม 3 ปี ค่าเทอม 280,000 บาท'; ",
  "  else detail = isTransfer ? 'เทียบโอนเหลือเรียน 3 ปี ค่าเทอมตลอดหลักสูตร 255,000 บาท' : 'เรียนเต็ม 4 ปี ค่าเทอมตลอดหลักสูตร 320,000 บาท'; ",
  "  facts = 'วิศวกรรมศาสตร์ หลักสูตร' + j.engineeringType + ' (เรียนออนไลน์+ออนไซต์ วันธรรมดาภาคค่ำ 19:00-21:00 ไม่ทุกวัน + วันอาทิตย์เต็มวันออนไลน์ เข้ามหาวิทยาลัยน้อยมาก) วุฒิลูกค้า=' + j.degree + ' ' + detail + '. เครื่องกลรับรองจากสภาวิศวกร ได้สิทธิ์สอบ กว. / ความปลอดภัยรับรองจากกรมสวัสดิการและคุ้มครองแรงงาน ได้ใบประกอบวิชาชีพ จป.เลยไม่ต้องสอบเพิ่ม ให้สรุปแล้วถามว่าสนใจสมัครเลยไหมคะ'; ",
  "} ",
  "else if (j.major === 'EdAdminMaster') { facts = 'ป.โทบริหารการศึกษา (เรียนวันอาทิตย์ 2 ปี, ค่าเทอม 150,000 บาท แบ่ง 7 งวด, ค่าสมัคร 1,500 บาท, ต้องมีใบประกอบวิชาชีพครู, หลักสูตรคุรุสภารับรอง, เมื่อเรียนจบสามารถนำวุฒิยื่นขอใบประกอบวิชาชีพผู้บริหารสถานศึกษาได้เลยไม่ต้องสอบเพิ่มเติม) ให้สรุปแล้วถามว่ามีใบประกอบวิชาชีพครูหรือยัง และถามว่าสนใจสมัครเลยไหมคะ'; } ",
  "else if (j.major === 'GradDip') { facts = 'ป.บัณฑิตวิชาชีพครู (ลูกค้าเป็นครูเครือ สพฐ. ผ่านเงื่อนไขแล้ว) เรียนออนไลน์เป็นหลัก วันเสาร์หรืออาทิตย์ขึ้นกับอาจารย์ผู้สอน เปิดภาคเรียนเดือนธันวาคม 2569 ค่าสมัคร 1,500 บาท ค่าเทอมตลอดหลักสูตร 54,000 บาท ผ่อนชำระรายเดือนได้ ระยะเวลา 1.5 ปี (3 เทอม) เข้าร่วมกิจกรรมที่มหาวิทยาลัยเทอมละ 1 ครั้ง (รวม 3 ครั้งตลอดหลักสูตร) หลักสูตรคุรุสภารับรอง เมื่อเรียนจบมีสิทธิ์สอบใบประกอบวิชาชีพครู ให้สรุปแล้วถามว่าสนใจสมัครเลยไหมคะ'; } ",
  "return facts; })()"
];
const promptExpr = promptParts.join('');

const jsonBodyValue = "={{ JSON.stringify({ model: 'gpt-4o-mini', temperature: 0.5, messages: [ { role: 'system', content: " + promptExpr + " }, ...$json.history ] }) }}";

const aiNode = wf.nodes.find(n => n.name === 'AI - Generate Reply');
aiNode.parameters.jsonBody = jsonBodyValue;

const saveNode = wf.nodes.find(n => n.name === 'Redis Save State');
saveNode.parameters.value = "={{ JSON.stringify({history: $json.history, major: $json.major, degree: $json.degree, job: $json.job, experience: $json.experience, grade: $json.grade, track: $json.track, age: $json.age, weight: $json.weight, height: $json.height, govOrPrivate: $json.govOrPrivate, pnTrack: $json.pnTrack, engineeringType: $json.engineeringType, isSpobTeacher: $json.isSpobTeacher, conversationEnded: $json.conversationEnded, detailGiven: $json.detailGiven}) }}";

const payload = { name: wf.name, nodes: wf.nodes, connections: wf.connections, settings: {} };
fs.writeFileSync('brain2_updated.json', JSON.stringify(payload));
console.log('hasNewlineInJsonBody:', /[\r\n]/.test(jsonBodyValue));
console.log('done, nodes count:', wf.nodes.length, 'jsonBody length:', jsonBodyValue.length);
