const fs = require('fs');
const wf = JSON.parse(fs.readFileSync('brain2_current.json', 'utf8'));

const extractCode = [
  "let state;",
  "try { state = JSON.parse($input.first().json.stateRaw || '{}'); } catch (e) { state = {}; }",
  "state.history = state.history || [];",
  "state.major = state.major || null; // RN, PN, HR, Engineering, EdAdminMaster, GradDip",
  "state.degree = state.degree || null;",
  "state.grade = state.grade || null;",
  "state.track = state.track || null;",
  "state.age = state.age || null;",
  "state.weight = state.weight || null;",
  "state.height = state.height || null;",
  "state.govOrPrivate = state.govOrPrivate || null;",
  "state.hrTrack = state.hrTrack || null; // HR เฉพาะวุฒิ ปวส./ป.ตรี: บริหารธุรกิจ, สังคม, วิทย์ (กำหนดระยะเวลาเรียนหลังเทียบโอน)",
  "state.hrExperienceYears = state.hrExperienceYears ?? null; // HR เฉพาะวุฒิ กศน./ม.6/ปวช.: ปีประสบการณ์ทำงาน (กำหนดระยะเวลาเรียนหลังเทียบโอน)",
  "state.pnTrack = state.pnTrack || null; // ปกติ, พิเศษ",
  "state.engineeringType = state.engineeringType || null; // เครื่องกล, ความปลอดภัย, 2ปริญญา",
  "state.isSpobTeacher = state.isSpobTeacher ?? null; // ป.บัณฑิต: เป็นครูผู้สอนในสถานศึกษา (สพฐ. หรือเอกชนที่มีการเรียนการสอนปกติ) หรือไม่",
  "state.eduHasLicense = state.eduHasLicense ?? null; // ป.โทบริหารการศึกษา: มีใบประกอบวิชาชีพครูหรือไม่ (เงื่อนไขจำเป็นจริงตามที่แอดมินคัดกรอง)",
  "state.pnDetailGiven = state.pnDetailGiven || false;",
  "state.eduDetailGiven = state.eduDetailGiven || false;",
  "state.gradDipDetailGiven = state.gradDipDetailGiven || false;",
  "state.engineeringDetailGiven = state.engineeringDetailGiven || false;",
  "state.hrDetailGiven = state.hrDetailGiven || false;",
  "state.conversationEnded = state.conversationEnded || false;",
  "state.detailGiven = state.detailGiven || false;",
  "state.wantsAdmin = false;",
  "",
  "const webhookBody = $('Webhook').first().json.body;",
  "const userId = webhookBody.userId;",
  "const channel = webhookBody.channel || 'general'; // 'general' หรือ 'nursing' ส่งมาจาก server.js",
  "const persona = channel === 'nursing' ? 'อาจารย์' : 'แอดมิน';",
  "const rawMessage = webhookBody.message || '';",
  "state.history.push({ role: 'user', content: rawMessage });",
  "",
  "const text = rawMessage.toLowerCase();",
  "// snapshot ก่อนแยกข้อมูล ใช้เช็คทีหลังว่าข้อความนี้ \"ให้ข้อมูลคัดกรองจริง\" หรือแค่ถามคำถามอื่นแทรก",
  "const fieldsBefore = JSON.stringify({major: state.major, degree: state.degree, grade: state.grade, track: state.track, age: state.age, weight: state.weight, height: state.height, govOrPrivate: state.govOrPrivate, pnTrack: state.pnTrack, engineeringType: state.engineeringType, isSpobTeacher: state.isSpobTeacher, eduHasLicense: state.eduHasLicense, hrTrack: state.hrTrack, hrExperienceYears: state.hrExperienceYears});",
  "// เช็คก่อนว่าเป็นคำถาม (มี ไหม/มั้ย/เท่าไหร่ ฯลฯ) เพื่อกันไม่ให้ regex จับสาขาแบบหลวมๆ (เช่น คำว่า \"พยาบาล\" ลอยๆ) ไปเข้าใจผิดว่าลูกค้าเลือกสาขา ทั้งที่จริงแค่ถามคำถามแทรก",
  "const hasQuestionMarker = /ไหม|มั้ย|ม้าย|หรอ|ป่าว|เท่าไหร่|เท่าไร|กี่|ยังไง|อย่างไร|ทำไม|ที่ไหน|เมื่อไหร่|รับรอง|ได้ไหม|ใช่ไหม|หรือเปล่า|ไหนคะ|ไหนครับ|บ้างคะ|บ้างครับ|อะไรบ้าง|เอกสาร/.test(text);",
  "const numbers = (rawMessage.match(/\\d+(\\.\\d+)?/g) || []).map(Number);",
  "const decimalNumbers = (rawMessage.match(/\\d\\.\\d+/g) || []).map(Number); // เก็บไว้แยกต่างหาก กันเคสเกรด 3.0 ถูกตัดทศนิยมจนตรวจไม่เจอ",
  "",
  "// ----- กฎช่องทาง: ห้ามพูดพยาบาลในเพจทั่วไป / ห้ามพูดสาขาอื่นในเพจพยาบาล -----",
  "const channelBlocked = (channel === 'general' && (text.includes('พยาบาล')))",
  "  || (channel === 'nursing' && state.major && !['RN','PN'].includes(state.major));",
  "",
  "// ----- ตรวจคำตอบรับสั้นๆ หลังจากให้รายละเอียดคอร์สไปแล้ว -----",
  "const confirmWords = ['สนใจ', 'ใสใจ', 'สนจ', 'ใช่', 'ตกลง', 'โอเค', 'เอาเลย', 'ครับสนใจ', 'อยากสมัคร', 'สมัคร'];",
  "// ลูกค้าตอบรับสั้นๆแค่ \"ครับ\"/\"ค่ะ\" เปล่าๆ (ไม่มีคำอื่นปน) หลังถูกถามว่าสนใจสมัครไหม ก็ถือเป็นการยืนยันด้วย",
  "const isBareYes = /^(ครับ|ค่ะ|คะ|ค่า)[\\s.!]*$/.test(text.trim());",
  "// ลูกค้าตอบสั้นๆแค่ \"ยังครับ\"/\"ยังค่ะ\" (ไม่มีคำอื่นปน) เวลาถูกถามคำถามใช่/ไม่ใช่ ก็หมายถึง \"ยังไม่มี/ยังไม่ใช่\" (ของจริงแอดมินตีความแบบนี้)",
  "const isBareNo = /^ยัง(ครับ|ค่ะ|คะ|ค่า)?[\\s.!]*$/.test(text.trim());",
  "if (state.detailGiven && !state.conversationEnded && (confirmWords.some(w => text.includes(w)) || isBareYes)) {",
  "  state.wantsAdmin = true;",
  "  const FORM_NURSING2 = 'https://forms.gle/MKg5NfUtvjj1xr2k7';",
  "  const FORM_ENGINEERING2 = 'https://forms.gle/nPJuM28hHuynxtp97';",
  "  const FORM_HR2 = 'https://forms.gle/YBXny8GdW1VAXocJ6';",
  "  const FORM_EDU2 = 'https://docs.google.com/forms/d/17Tq151nb8UH2C5QyL1EF922PzHrpGA_bCJhd7tnToLQ/viewform';",
  "  const QR_PAYMENT2 = 'https://raw.githubusercontent.com/pakasit14-Sayfa/shinawatra-chatbot/main/backend-middleware/public/images/shinawatra/payment-qr.png';",
  "  const formLink2 = ['RN','PN'].includes(state.major) ? FORM_NURSING2 : (state.major === 'Engineering' ? FORM_ENGINEERING2 : (state.major === 'HR' ? FORM_HR2 : (['EdAdminMaster','GradDip'].includes(state.major) ? FORM_EDU2 : null)));",
  "  if (formLink2) {",
  "    state.forcedAnswer = 'อาจารย์ส่งแบบฟอร์มการกรอกข้อมูลการสมัครนะคะ\\n' + formLink2 + '\\n![QR ชำระเงิน](' + QR_PAYMENT2 + ')\\n===\\nลูกชำระค่าสมัครเรียบร้อยแล้วแจ้งอาจารย์นะคะ อาจารย์นำรายชื่อเข้าระบบให้ก่อนค่ะ ส่วนเอกสารที่ขาดสามารถแนบในฟอร์มภายหลังได้ค่ะลูก';",
  "  }",
  "}",
  "",
  "// ----- ดึงสาขาที่สนใจ (deterministic) -----",
  "state.multiProgramOptions = null;",
  "if (!state.major && !channelBlocked && !hasQuestionMarker) {",
  "  if (channel === 'nursing' || text.includes('พยาบาล')) {",
  "    const says1Year = /1\\s*ปี/.test(text);",
  "    const looksLikePN = text.includes('ผู้ช่วย') || /\\bpn\\b/.test(text) || says1Year;",
  "    const looksLikeRN = /\\brn\\b/.test(text) || text.includes('พยาบาลศาสตร์') || (text.includes('พยาบาล') && !text.includes('ผู้ช่วย'));",
  "    if (looksLikePN && looksLikeRN) {",
  "      // ลูกค้าพูดถึงทั้ง RN และ PN พร้อมกัน ห้ามเดาเลือกให้เอง ต้องถามยืนยันก่อน",
  "      state.multiProgramOptions = ['RN', 'PN'];",
  "    } else if (looksLikePN) { state.major = 'PN'; }",
  "    else if (looksLikeRN) { state.major = 'RN'; }",
  "    // ถ้าพิมพ์ \"พยาบาล\" ลอยๆ ไม่ระบุ ให้รอถามก่อน (major ยังเป็น null)",
  "  } else if (text.includes('ทรัพยากรมนุษย์') || text.includes('การจัดการ') || /ฝ่ายบุคคล|งานบุคคล|แผนกบุคคล/.test(text) || /\\bhr\\b/.test(text)) {",
  "    state.major = 'HR';",
  "  } else if (text.includes('วิศว') || text.includes('เครื่องกล') || text.includes('ความปลอดภัย') || /2\\s*ปริญญา|สองปริญญา|ปริญญาคู่|2\\s*ใบ|สองใบ/.test(text)) {",
  "    state.major = 'Engineering';",
  "  } else if (text.includes('บริหารการศึกษา') || text.includes('ป.โท')) {",
  "    state.major = 'EdAdminMaster';",
  "  } else if (text.includes('ป.บัณฑิต') || text.includes('บัณฑิตวิชาชีพครู')) {",
  "    state.major = 'GradDip';",
  "  }",
  "}",
  "",
  "if (state.multiProgramOptions) {",
  "  state.forcedAnswer = 'นักศึกษาสนใจสอบถามหลายหลักสูตรพร้อมกันเลยนะคะ เพื่อให้อาจารย์ให้ข้อมูลได้ตรงที่สุด รบกวนเลือกก่อนนะคะว่าสนใจหลักสูตรพยาบาล (RN 4ปี) หรือหลักสูตรผู้ช่วยพยาบาล (PN 1ปี) เป็นพิเศษ';",
  "}",
  "",
  "// ----- ดึงวุฒิการศึกษา -----",
  "if (!state.degree) {",
  "  if (/กศน/.test(text)) state.degree = 'กศน.';",
  "  else if (/ม\\.?6|มัธยมศึกษาปีที่\\s*6|มัธยมปลาย/.test(text)) state.degree = 'ม.6';",
  "  else if (/ปวช/.test(text)) state.degree = 'ปวช.';",
  "  else if (/ปวส/.test(text)) state.degree = 'ปวส.';",
  "  else if (/ป\\.?ตรี|ปริญญาตรี|bachelor/.test(text)) state.degree = 'ปริญญาตรี';",
  "  else if (/ม\\.?\\s*[1-5]\\b|มัธยมต้น|มัธยมศึกษาปีที่\\s*[1-5]\\b|ป\\.?\\s*[1-6]\\b|ประถม/.test(text)) { state.degree = 'ต่ำกว่าเกณฑ์'; state.conversationEnded = true; }",
  "}",
  "if (['RN','PN'].includes(state.major) && state.degree === 'ต่ำกว่าเกณฑ์' && !state.forcedAnswer) {",
  "  state.forcedAnswer = 'หลักสูตรนี้รับสมัครขั้นต่ำที่วุฒิ ม.6 หรือเทียบเท่าเท่านั้นนะคะ วุฒิที่นักศึกษาแจ้งมายังไม่ถึงเกณฑ์ที่กำหนด ต้องขออภัยด้วยนะคะ';",
  "}",
  "if (!state.job && /ทำงาน|รับราชการ|พนักงาน|ธุรกิจส่วนตัว|อาชีพ|ครู/.test(text)) state.job = rawMessage;",
  "if (!state.experience && /ปี|ปีแล้ว|ประสบการณ์/.test(text)) state.experience = rawMessage;",
  "",
  "// ----- RN และ PN: เกรด/สาย/อายุ/น้ำหนัก/ส่วนสูง (เก็บข้อมูลเหมือนกัน แต่ PN ไม่มีเกณฑ์ตัดสิทธิ์) -----",
  "// เก็บได้ตลอดเวลาไม่ต้องรอรู้สาขาก่อน (ลูกค้าบางคนให้ข้อมูลมาก่อนบอกว่าเลือก RN/PN)",
  "{",
  "  if (!state.track) {",
  "    if (/วิทย์|วิทยาศาสตร์/.test(text)) state.track = 'วิทย์-คณิต';",
  "    else if (/สังคม|ศิลป์|ภาษา|ศิลภาษา/.test(text)) state.track = 'สายอื่นๆ';",
  "  }",
  "  if (state.grade === null) {",
  "    // ลองจับเลขทศนิยม (3.0) ก่อน ถ้าไม่มีค่อย fallback ไปจับเลขเต็มจำนวนเดี่ยวๆ (เช่น ลูกค้าพิมพ์แค่ \"3\") เพราะไม่มีฟิลด์อื่นที่ค่าอยู่ในช่วง 0-4 เลย ไม่เสี่ยงชนกับอายุ/น้ำหนัก/ส่วนสูง",
  "    let g = decimalNumbers.find(n => n >= 0 && n <= 4);",
  "    if (g === undefined) g = numbers.find(n => n >= 0 && n <= 4 && Number.isInteger(n));",
  "    if (g !== undefined) state.grade = g;",
  "  }",
  "  if (state.age === null) {",
  "    // ลองจับเลขที่อยู่ติดกับคำว่า \"อายุ\" ก่อน (แม่นยำกว่า) ถ้าไม่มีคำนี้ค่อย fallback ไปหาเลขในช่วงที่เข้าเกณฑ์",
  "    const ageNear = text.match(/อายุ\\D{0,5}(\\d{1,3})/);",
  "    if (ageNear && Number(ageNear[1]) >= 10 && Number(ageNear[1]) <= 100) state.age = Number(ageNear[1]);",
  "    else { const a = numbers.find(n => n >= 10 && n <= 100 && Number.isInteger(n)); if (a !== undefined) state.age = a; }",
  "  }",
  "  if (state.weight === null) {",
  "    const weightNear = text.match(/(?:น้ำหนัก|หนัก)\\D{0,5}(\\d{1,3}(?:\\.\\d+)?)/);",
  "    if (weightNear && Number(weightNear[1]) >= 20 && Number(weightNear[1]) <= 200) state.weight = Number(weightNear[1]);",
  "    else { const w = numbers.find(n => n >= 30 && n <= 150); if (w !== undefined) state.weight = w; }",
  "  }",
  "  if (state.height === null) {",
  "    const heightNear = text.match(/(?:ส่วนสูง|สูง)\\D{0,5}(\\d{2,3}(?:\\.\\d+)?)/);",
  "    if (heightNear && Number(heightNear[1]) >= 100 && Number(heightNear[1]) <= 250) state.height = Number(heightNear[1]);",
  "    else { const h = numbers.find(n => n >= 140 && n <= 210); if (h !== undefined) state.height = h; }",
  "  }",
  "}",
  "// RN รับเฉพาะวุฒิ ม.6 (สายสามัญ) เท่านั้น สายอาชีพ (ปวช./ปวส./ป.ตรี) และ กศน. ไม่รับ",
  "if (state.major === 'RN' && state.degree && state.degree !== 'ม.6' && !state.conversationEnded) {",
  "  state.conversationEnded = true;",
  "  state.forcedAnswer = 'หลักสูตรพยาบาล (RN) รับเฉพาะวุฒิ ม.6 สายสามัญเท่านั้นนะคะ วุฒิที่นักศึกษาแจ้งมายังไม่สามารถสมัครหลักสูตรนี้ได้ ต้องขออภัยด้วยนะคะ หากนักศึกษาสนใจหลักสูตรผู้ช่วยพยาบาล (PN) แทน สามารถแจ้งอาจารย์ได้เลยนะคะ';",
  "}",
  "",
  "// ----- เฉพาะ PN: เลือกภาคปกติ/พิเศษ -----",
  "if (state.major === 'PN' && !state.pnTrack) {",
  "  const saysSpecial = /พิเศษ|เสาร์|อาทิตย์/.test(text);",
  "  const saysNormal = /ปกติ|จันทร์|ศุกร์/.test(text);",
  "  // ถ้าพูดถึงทั้ง 2 ภาคพร้อมกัน (เช่น คำถามเปรียบเทียบ \"ปกติกับพิเศษต่างกันยังไง\") ห้ามเดาเลือกให้เอง ต้องถามยืนยันก่อน",
  "  if (saysSpecial && saysNormal) { /* ไม่เลือก รอลูกค้าระบุให้ชัดก่อน */ }",
  "  else if (saysSpecial) { state.pnTrack = 'พิเศษ'; }",
  "  else if (saysNormal) { state.pnTrack = 'ปกติ'; }",
  "}",
  "",
  "// ----- เฉพาะ Engineering: เลือกหลักสูตร (เครื่องกล/ความปลอดภัย/2ปริญญา) -----",
  "if (state.major === 'Engineering' && !state.engineeringType) {",
  "  const hasMech = /เครื่องกล/.test(text);",
  "  const hasSafety = /ความปลอดภัย/.test(text);",
  "  const saysDual = /2\\s*ปริญญา|สองปริญญา|ปริญญาคู่|2\\s*ใบ|สองใบ/.test(text);",
  "  // ถ้าพูดถึงทั้งเครื่องกลและความปลอดภัยพร้อมกัน (เช่น คำถามเปรียบเทียบ \"เครื่องกลกับความปลอดภัยต่างกันยังไง\") โดยไม่ได้ระบุ \"2 ปริญญา\" ชัดเจน ห้ามเดาเลือกให้เอง",
  "  if (hasMech && hasSafety && !saysDual) { /* ไม่เลือก รอลูกค้าระบุให้ชัดก่อน */ }",
  "  else if (saysDual) { state.engineeringType = '2ปริญญา'; }",
  "  else if (hasMech) { state.engineeringType = 'เครื่องกล'; }",
  "  else if (hasSafety) { state.engineeringType = 'ความปลอดภัย'; }",
  "}",
  "",
  "// ----- เฉพาะ HR: ที่ทำงานรัฐ/เอกชน (ไม่มีงานทำ ถือเกณฑ์เดียวกับเอกชน ตามตารางจริง) -----",
  "if (state.major === 'HR' && !state.govOrPrivate) {",
  "  const saysGov = /รัฐ|ราชการ|รัฐวิสาหกิจ/.test(text);",
  "  const saysPrivate = /เอกชน|บริษัท|ไม่มีงาน|ไม่ได้ทำงาน|ว่างงาน/.test(text);",
  "  // ถ้าพูดถึงทั้งรัฐและเอกชนพร้อมกัน (เช่น คำถามเปรียบเทียบ \"รัฐกับเอกชนต่างกันยังไง\") ห้ามเดาเลือกให้เอง",
  "  if (saysGov && saysPrivate) { /* ไม่เลือก รอลูกค้าระบุให้ชัดก่อน */ }",
  "  else if (saysGov) { state.govOrPrivate = 'รัฐ'; }",
  "  else if (saysPrivate) { state.govOrPrivate = 'เอกชน'; }",
  "}",
  "",
  "// ----- เฉพาะ HR วุฒิ ปวส./ป.ตรี: สายที่จบ (กำหนดระยะเวลาเทียบโอนตามตารางจริง) -----",
  "if (state.major === 'HR' && ['ปวส.','ปริญญาตรี'].includes(state.degree) && !state.hrTrack) {",
  "  const saysBiz = /บริหารธุรกิจ|บัญชี|การจัดการ|การตลาด|เศรษฐศาสตร์/.test(text);",
  "  const saysSocial = /สังคม|ศิลป์|มนุษย์|รัฐศาสตร์|นิติ|ครุ|ศึกษาศาสตร์/.test(text);",
  "  const saysScience = /วิทย์|วิทยาศาสตร์|วิศวกรรม|เทคโนโลยี|คอมพิวเตอร์/.test(text);",
  "  const hitCount = [saysBiz, saysSocial, saysScience].filter(Boolean).length;",
  "  // ถ้าพูดถึงมากกว่า 1 สายพร้อมกัน (กำกวม) ห้ามเดาเลือกให้เอง",
  "  if (hitCount === 1) {",
  "    state.hrTrack = saysBiz ? 'บริหารธุรกิจ' : (saysSocial ? 'สังคม' : 'วิทย์');",
  "  }",
  "}",
  "",
  "// ----- เฉพาะ HR วุฒิ กศน./ม.6/ปวช.: ปีประสบการณ์ทำงาน (กำหนดระยะเวลาเทียบโอนตามตารางจริง) -----",
  "if (state.major === 'HR' && state.degree && !['ปวส.','ปริญญาตรี'].includes(state.degree) && state.hrExperienceYears === null) {",
  "  const expMatch = text.match(/(?:ประสบการณ์|ทำงาน)\\D{0,10}(\\d{1,2})\\s*ปี/);",
  "  if (expMatch) state.hrExperienceYears = Number(expMatch[1]);",
  "  else if (/ไม่มีประสบการณ์|ไม่เคยทำงาน|ยังไม่ได้ทำงาน|ไม่มีประสบการ/.test(text)) state.hrExperienceYears = 0;",
  "}",
  "",
  "// ----- เฉพาะ GradDip: เป็นครูผู้สอนในสถานศึกษาหรือไม่ (สพฐ. หรือเอกชนที่มีการเรียนการสอนปกติ ก็เข้าเงื่อนไขได้ ไม่ใช่แค่ สพฐ.) -----",
  "if (state.major === 'GradDip' && state.isSpobTeacher === null) {",
  "  if (/ไม่ใช่|ไม่ได้เป็น|ไม่มี/.test(text) || isBareNo) state.isSpobTeacher = false;",
  "  else if (/(?<!วิชาชีพ)ครู|ใช่|สพฐ|เอกชน/.test(text)) state.isSpobTeacher = true;",
  "}",
  "if (state.major === 'GradDip' && state.isSpobTeacher === false && !state.conversationEnded) {",
  "  state.conversationEnded = true;",
  "  state.forcedAnswer = 'ขออภัยในความไม่สะดวกด้วยนะคะ เนื่องจากหลักสูตรนี้ทางคุรุสภาได้ออกเงื่อนไขมาว่าจำเป็นจะต้องเป็นผู้ที่เป็นครูที่ทำงานอยู่ในสถานศึกษาเท่านั้นนะคะ ดังนั้นหากไม่ได้อยู่ในเงื่อนไขดังกล่าวจะไม่สามารถเรียนได้ค่ะ';",
  "}",
  "",
  "// ----- เฉพาะ EdAdminMaster: มีใบประกอบวิชาชีพครูหรือไม่ (เงื่อนไขจำเป็นจริงตามที่แอดมินคัดกรอง) -----",
  "if (state.major === 'EdAdminMaster' && state.eduHasLicense === null) {",
  "  if (/ไม่มี|ยังไม่มี|ไม่ได้มี/.test(text) || isBareNo) state.eduHasLicense = false;",
  "  else if (/มีแล้ว|มีค่ะ|มีครับ|^มี\\b|มีใบ/.test(text)) state.eduHasLicense = true;",
  "}",
  "if (state.major === 'EdAdminMaster' && state.eduHasLicense === false) state.conversationEnded = true;",
  "",
  "// ----- เช็คว่าข้อมูลครบหรือยังตาม major -----",
  "function infoCompleteFor(major) {",
  "  if (major === 'RN' || major === 'PN') {",
  "    // \"สายการเรียน\" (วิทย์/ศิลป์) ต้องเก็บแค่ RN เท่านั้น (รับแค่ ม.6) ส่วน PN ไม่ต้องเก็บเลยไม่ว่าวุฒิจะเป็นอะไร",
  "    const trackOk = major === 'RN' ? !!state.track : true;",
  "    // เกรดใช้ตัดสิทธิ์จริงแค่ RN เท่านั้น (pnFailReasons ไม่เคยเช็คเกรด) PN ไม่ต้องรอเกรดถึงจะถือว่าข้อมูลครบ",
  "    const gradeOk = major === 'RN' ? state.grade !== null : true;",
  "    return !!(state.degree && gradeOk && trackOk && state.age !== null && state.weight !== null && state.height !== null);",
  "  }",
  "  if (major === 'HR') {",
  "    if (!state.degree || !state.govOrPrivate) return false;",
  "    return ['ปวส.','ปริญญาตรี'].includes(state.degree) ? !!state.hrTrack : state.hrExperienceYears !== null;",
  "  }",
  "  if (major === 'Engineering') return !!(state.degree && state.engineeringType);",
  "  if (major === 'EdAdminMaster') return state.eduHasLicense === true;",
  "  if (major === 'GradDip') return state.isSpobTeacher !== null;",
  "  return false;",
  "}",
  "const infoComplete = state.major ? infoCompleteFor(state.major) : false;",
  "// RN/PN ข้อมูลยังไม่ครบ -> ส่งคำถามแบบตายตัวเสมอ (ไม่ผ่าน AI เด็ดขาด กัน AI วนตอบฟอร์มเปล่าซ้ำทั้งที่มีข้อมูลแล้วบางส่วน)",
  "// ถ้ายังไม่ต้องใช้สายการเรียน (วุฒิไม่ใช่ ม.6) ไม่ต้องถามช่องนี้เลย",
  "if (['RN','PN'].includes(state.major) && !infoComplete && !state.conversationEnded) {",
  "  const needsTrack = state.major === 'RN'; // เฉพาะ RN เท่านั้น (รับแค่ ม.6) PN ไม่ต้องเก็บสายการเรียนเลยไม่ว่าวุฒิจะเป็นอะไร",
  "  const needsGrade = state.major === 'RN'; // เกรดใช้ตัดสิทธิ์จริงแค่ RN เท่านั้น PN ไม่ต้องถามเกรดเลย",
  "  const rows = [",
  "    '- จบวุฒิการศึกษา = ' + (state.degree || ''),",
  "  ];",
  "  if (needsGrade) rows.push('- เกรดเฉลี่ย = ' + (state.grade !== null ? state.grade : ''));",
  "  if (needsTrack) rows.push('- สายการเรียน = ' + (state.track || ''));",
  "  rows.push('- อายุ = ' + (state.age !== null ? state.age : ''));",
  "  rows.push('- น้ำหนัก = ' + (state.weight !== null ? state.weight : ''));",
  "  rows.push('- ส่วนสูง = ' + (state.height !== null ? state.height : ''));",
  "  state.forcedAnswer = 'อาจารย์ขอสอบถามข้อมูลเบื้องต้นของนักศึกษาก่อนนะคะ\\n' + rows.join('\\n') + '\\nนักศึกษาแจ้งข้อมูลที่ยังขาดเพื่อประเมินคุณสมบัติได้เลยนะคะ';",
  "}",
  "",
  "// ----- ถ้าครบแล้วและเป็น RN ให้คำนวณเกณฑ์แบบ deterministic -----",
  "let rnEligible = null;",
  "let rnFailReasons = [];",
  "if (state.major === 'RN' && infoComplete && !state.conversationEnded) {",
  "  const heightM = state.height / 100;",
  "  const bmi = state.weight / (heightM * heightM);",
  "  const gradeMin = state.track === 'วิทย์-คณิต' ? 2.00 : 2.50;",
  "  if (!(bmi >= 17.5 && bmi <= 30)) rnFailReasons.push('BMI');",
  "  if (!(state.height >= 150)) rnFailReasons.push('ส่วนสูง');",
  "  if (!(state.weight >= 40)) rnFailReasons.push('น้ำหนัก');",
  "  if (!(state.age >= 16 && state.age <= 30)) rnFailReasons.push('อายุ');",
  "  if (!(state.grade >= gradeMin)) rnFailReasons.push('เกรดเฉลี่ย');",
  "  rnEligible = rnFailReasons.length === 0;",
  "}",
  "// ผ่านเกณฑ์ RN -> ส่งข้อความ+รูปแบบตายตัว ไม่ผ่าน -> ส่งต่อแอดมินทันที (ตามสเปคที่ทีมให้มา)",
  "if (state.major === 'RN' && infoComplete && !state.detailGiven) {",
  "  state.forcedAnswer = rnEligible",
  "    ? 'เกณฑ์คุณสมบัติเบื้องต้นผ่านนะคะ อาจารยส่งรายละเอียดให้ค่ะ\\n===\\n![ตารางผ่อนชำระกรณีกู้ กยศ.](https://raw.githubusercontent.com/pakasit14-Sayfa/shinawatra-chatbot/main/backend-middleware/public/images/shinawatra/nursing/rn-loan-installment-table.jpg)\\n===\\nนักศึกษาสามารถทำเรื่องยื่นกู้ กยศ. เพื่อลดภาระค่าเทอมได้ค่ะ แต่ในการยื่นกู้ทาง กยศ. จะเป็นคนพิจารณาอีกครั้งว่าจะผ่านไม่ผ่านค่ะ ในกรณีกู้ กยศ. แล้วผ่านไม่ต้องสำรองจ่าย ชำระเพียงค่าส่วนต่างเท่านั้นนะคะ แต่ในส่วนที่ยื่นแล้วผลไม่ผ่านนักศึกษาจะต้องมีสำรองจ่ายไว้ค่ะ\\n\\nค่าสมัครเพียง 1,000 บาทเท่านั้นค่ะ ชำระผ่านบัญชีธนาคารของมหาวิทยาลัยโดยตรงค่ะ\\n===\\nถ้าหากนักศึกษาสนใจสมัคร แจ้งอาจารย์ได้ในแชทนี้เลยนะคะ อาจารย์จะมีฟอร์มให้นักศึกษากรอกข้อมูลการสมัครค่ะ'",
  "    : 'เดี๋ยวอาจารย์ติดต่อไปให้ข้อมูลเพิ่มเติมนะคะ';",
  "}",
  "",
  "// ----- PN: เกณฑ์อายุ/ส่วนสูง/น้ำหนักตัดสิทธิ์ได้ ส่วน BMI แค่ข้อมูลไว้พูดคุย ไม่ตัดสิทธิ์ -----",
  "let pnEligible = null;",
  "let pnFailReasons = [];",
  "if (state.major === 'PN' && infoComplete) {",
  "  if (!(state.height >= 150)) pnFailReasons.push('ส่วนสูง');",
  "  if (!(state.weight >= 40)) pnFailReasons.push('น้ำหนัก');",
  "  if (!(state.age >= 16 && state.age <= 60)) pnFailReasons.push('อายุ');",
  "  pnEligible = pnFailReasons.length === 0;",
  "}",
  "if (state.major === 'PN' && infoComplete && !state.detailGiven) {",
  "  state.forcedAnswer = pnEligible",
  "    ? 'เกณฑ์คุณสมบัติเบื้องต้นผ่านนะคะ อาจารยส่งรายละเอียดให้ค่ะ\\n===\\n![ตารางค่าเทอมผู้ช่วยพยาบาล](https://raw.githubusercontent.com/pakasit14-Sayfa/shinawatra-chatbot/main/backend-middleware/public/images/shinawatra/nursing/pn-tuition-table.jpg)\\n===\\n📢 ขณะนี้หลักสูตรผู้ช่วยพยาบาล สามารถดำเนินการยื่นกู้กองทุนเงินให้กู้ยืมเพื่อการศึกษา (กยศ.) ได้แล้ว\\n- นักศึกษาสามารถกู้ยืมได้สูงสุด 50,000 บาท ตลอดหลักสูตร (การกู้ กยศ.จะขึ้นอยู่กับการพิจารณาของทาง กยศ.เท่านั้น)\\n- สำหรับภาคเรียนที่ 1 มีค่าใช้จ่ายส่วนต่างที่นักศึกษาต้องชำระเพิ่มเติมจำนวน 31,000 บาท (รวมค่าสมัคร 500 บาท)\\n- สำหรับค่าเล่าเรียน ภาคเรียนที่ 2 และ 3 นักศึกษาจำเป็นต้องสำรองชำระค่าใช้จ่ายล่วงหน้า จำนวน 50,000 บาท\\n\\nรายละเอียดการชำระค่าเล่าเรียน ภาคเรียนที่ 1 มีดังนี้\\n1. ชำระค่าสมัครจำนวน 500 บาท ในวันสมัคร เพื่อให้ทางอาจารย์ดำเนินการจัดทำเอกสารและบันทึกรายชื่อเข้าสู่ระบบรับสมัครของมหาวิทยาลัย\\n2. ชำระค่าเล่าเรียน ภาคเรียนที่ 1 งวดที่ 1 จำนวน 5,000 บาท ภายใน 1 สัปดาห์ หลังจากชำระค่าสมัครเรียบร้อยแล้ว\\n3. ชำระค่าเล่าเรียน ภาคเรียนที่ 1 งวดที่ 2 จำนวน 10,000 บาท ภายใน 1 สัปดาห์ หลังจากรายงานตัวเรียบร้อยแล้ว (หรือสามารถชำระพร้อมกันได้ตามความสะดวก)\\n4. ค่าเล่าเรียน ภาคเรียนที่ 1 ส่วนที่เหลือจำนวน 15,500 บาท สามารถทยอยชำระให้ครบก่อนวันเปิดภาคเรียน\\n===\\nถ้าหากนักศึกษาสนใจสมัคร แจ้งอาจารย์ได้ในแชทนี้เลยนะคะ อาจารย์จะมีฟอร์มให้นักศึกษากรอกข้อมูลการสมัครค่ะ'",
  "    : 'เดี๋ยวอาจารย์ติดต่อไปให้ข้อมูลเพิ่มเติมนะคะ';",
  "}",
  "",
  "// ให้รายละเอียดคอร์ส PN แบบตายตัว (จัดบรรทัด/bullet เหมือนสไตล์ RN) เพื่อความแน่นอน ไม่ผ่าน AI",
  "if (state.major === 'PN' && pnEligible && state.pnTrack && !state.pnDetailGiven) {",
  "  const pnLocation = state.pnTrack === 'พิเศษ' ? 'อาคาร OAI ย่านอโศก กรุงเทพมหานคร (เข้าแลบ/ฝึกงานต้องไปปทุมธานี)' : 'มหาวิทยาลัยชินวัตร จังหวัดปทุมธานี';",
  "  state.forcedAnswer = 'คุณสมบัติเบื้องต้นของลูกผ่านแล้วนะคะ\\nอาจารย์ขอสรุปรายละเอียดหลักสูตรผู้ช่วยพยาบาล ภาค' + state.pnTrack + ' ให้นะคะ\\n- ระยะเวลาเรียน: 1 ปี\\n- สถานที่เรียน: ' + pnLocation + '\\n- ค่าสมัคร: 500 บาท\\n- ค่าใช้จ่ายภาคเรียนที่ 1: 31,000 บาท (รวมค่าสมัครแล้ว)\\n- ภาคเรียนที่ 2-3: สำรองชำระล่วงหน้า 50,000 บาท\\n- กู้ กยศ. ได้สูงสุด 50,000 บาทตลอดหลักสูตร (อนุมัติตามเงื่อนไข กยศ.)\\nสนใจสมัครเลยไหมคะ';",
  "  state.pnDetailGiven = true;",
  "}",
  "",
  "// ถามข้อมูลที่ยังขาดของ ป.โทบริหารการศึกษา แบบตายตัว ไม่ผ่าน AI เด็ดขาด",
  "// (เคยให้ AI พิมพ์เองแล้วพบจริงว่า AI มั่วตอบว่า \"ข้อมูลครบแล้ว สมัครได้เลย\" ทั้งที่วุฒิยังไม่ได้ถาม ทำให้ลูกค้าหลงคิดว่าจบขั้นตอนแล้ว)",
  "if (state.major === 'EdAdminMaster' && state.eduHasLicense === null && !state.conversationEnded) {",
  "  state.forcedAnswer = 'อาจารย์ขอสอบถามนะคะ นักศึกษามีใบประกอบวิชาชีพครูแล้วหรือยังคะ';",
  "}",
  "",
  "// ให้รายละเอียดคอร์ส ป.โทบริหารการศึกษา แบบตายตัว จัดบรรทัดด้วยอีโมจิหมวด (สไตล์เดียวกับที่แอดมินจริงใช้)",
  "if (state.major === 'EdAdminMaster' && infoComplete && !state.eduDetailGiven) {",
  "  const EDU_IMG = 'https://raw.githubusercontent.com/pakasit14-Sayfa/shinawatra-chatbot/main/backend-middleware/public/images/shinawatra/master/edu-admin-master-info.jpg';",
  "  state.forcedAnswer = 'อาจารย์ขอสรุปรายละเอียดหลักสูตรปริญญาโท สาขาบริหารการศึกษาให้นะคะ\\n📍 สถานที่เรียน: มหาวิทยาลัยชินวัตร (เรียนได้ทั้งรูปแบบ Online และ Onsite)\\n🗓 วันและเวลาเรียน: เฉพาะวันอาทิตย์ เวลา 09.00-16.00 น. ระยะเวลาในการศึกษา 2 ปี\\nคุณสมบัติของผู้สมัคร\\n- เป็นครูหรือบุคลากรทางการศึกษา\\n- สำเร็จการศึกษาระดับปริญญาตรีในทุกสาขาวิชา\\n- มีใบอนุญาตประกอบวิชาชีพครู\\n💰 ค่าใช้จ่ายตลอดหลักสูตร: 150,000 บาท แบ่งชำระได้ 7 งวด\\n- 6 งวดแรก ชำระงวดละ 21,000 บาท\\n- งวดสุดท้าย ชำระ 24,000 บาท\\n📄 ค่าสมัครเรียน: 1,500 บาทเท่านั้นค่ะ\\n===\\n![โครงสร้างหลักสูตรและการรับรองคุรุสภา ป.โทบริหารการศึกษา](' + EDU_IMG + ')\\n===\\nนักศึกษาสนใจสมัครเลยไหมคะ';",
  "  state.eduDetailGiven = true;",
  "}",
  "",
  "// ให้รายละเอียดคอร์ส ป.บัณฑิตวิชาชีพครู แบบตายตัว จัดบรรทัดด้วยอีโมจิหมวด (สไตล์เดียวกับที่แอดมินจริงใช้)",
  "if (state.major === 'GradDip' && state.isSpobTeacher === true && !state.gradDipDetailGiven) {",
  "  const GRADDIP_IMG = 'https://raw.githubusercontent.com/pakasit14-Sayfa/shinawatra-chatbot/main/backend-middleware/public/images/shinawatra/graddip/tuition-table.jpg';",
  "  state.forcedAnswer = 'อาจารย์ขอสรุปรายละเอียดหลักสูตรป.บัณฑิตวิชาชีพครูให้นะคะ\\n📍 รูปแบบเรียน: ออนไลน์เป็นหลัก วันเสาร์หรืออาทิตย์ตามอาจารย์ผู้สอน\\n🗓 เปิดภาคเรียน: เดือนธันวาคม 2569 ระยะเวลาเรียน 1.5 ปี (3 เทอม)\\nคุณสมบัติของผู้สมัคร\\n- เป็นครูผู้สอนในโรงเรียน สพฐ. หรือเอกชนที่มีการเรียนการสอนปกติ\\n- ต้องเข้าร่วมกิจกรรมที่มหาวิทยาลัยเทอมละ 1 ครั้ง (รวม 3 ครั้งตลอดหลักสูตร)\\n💰 ค่าใช้จ่ายตลอดหลักสูตร: 54,000 บาท ผ่อนชำระรายเดือนได้\\n📄 ค่าสมัครเรียน: 1,500 บาทเท่านั้นค่ะ\\n🎓 การรับรอง: หลักสูตรคุรุสภารับรอง เรียนจบมีสิทธิ์สอบใบประกอบวิชาชีพครู\\n===\\n![ตารางค่าเทอม ป.บัณฑิตวิชาชีพครู](' + GRADDIP_IMG + ')\\n===\\nนักศึกษาสนใจสมัครเลยไหมคะ';",
  "  state.gradDipDetailGiven = true;",
  "}",
  "",
  "// ให้รายละเอียดคอร์สวิศวกรรมศาสตร์ แบบตายตัว แนบตารางค่าเทอมตามวุฒิ+หลักสูตรที่เลือก",
  "if (state.major === 'Engineering' && infoComplete && !state.engineeringDetailGiven) {",
  "  const isTransfer = ['ปวส.','ปริญญาตรี'].includes(state.degree);",
  "  const ENG_BASE = 'https://raw.githubusercontent.com/pakasit14-Sayfa/shinawatra-chatbot/main/backend-middleware/public/images/shinawatra/engineering/';",
  "  const engImgKey = state.engineeringType === 'เครื่องกล' ? 'mechanical' : (state.engineeringType === 'ความปลอดภัย' ? 'safety' : 'dual');",
  "  const engImg = ENG_BASE + engImgKey + '-' + (isTransfer ? 'transfer' : 'full') + '.jpg';",
  "  const certLine = state.engineeringType === 'เครื่องกล' ? 'รับรองจากสภาวิศวกร ได้สิทธิ์สอบ กว.'",
  "    : (state.engineeringType === 'ความปลอดภัย' ? 'รับรองจากกรมสวัสดิการและคุ้มครองแรงงาน ได้ใบประกอบวิชาชีพ จป.เลยไม่ต้องสอบเพิ่ม'",
  "    : 'เครื่องกลรับรองจากสภาวิศวกร ได้สิทธิ์สอบ กว. และความปลอดภัยรับรองจากกรมสวัสดิการและคุ้มครองแรงงาน ได้ใบประกอบวิชาชีพ จป.เลยไม่ต้องสอบเพิ่ม');",
  "  let durationLine;",
  "  if (state.engineeringType === '2ปริญญา') durationLine = isTransfer ? 'เทียบโอนเหลือเรียน 3 ปี ค่าเทอมตลอดหลักสูตร 255,000 บาท' : 'เรียนเต็ม 4 ปี ค่าเทอมตลอดหลักสูตร 320,000 บาท';",
  "  else durationLine = isTransfer ? 'เทียบโอนเหลือเรียน 2 ปี ค่าเทอมเหมาจ่ายตลอดหลักสูตร 150,000 บาท' : 'เรียนเต็ม 4 ปี ค่าเทอมตลอดหลักสูตร 280,000 บาท';",
  "  state.forcedAnswer = 'อาจารย์ขอสรุปรายละเอียดหลักสูตรวิศวกรรมศาสตร์ ' + state.engineeringType + ' ให้นะคะ\\n\\n📍 รูปแบบเรียน: ออนไลน์+ออนไซต์ วันธรรมดาภาคค่ำ 19:00-21:00 ไม่ทุกวัน และวันอาทิตย์เต็มวันออนไลน์ เข้ามหาวิทยาลัยน้อยมาก\\n\\n🗓 ระยะเวลาเรียนและค่าเทอม: ' + durationLine + '\\n\\n🎓 การรับรอง: ' + certLine + '\\n\\n===\\n![ตารางค่าเทอมวิศวกรรมศาสตร์ ' + state.engineeringType + '](' + engImg + ')\\n===\\n\\nนักศึกษาสนใจสมัครเลยไหมคะ';",
  "  state.engineeringDetailGiven = true;",
  "}",
  "",
  "// ----- HR: ถามข้อมูลที่ยังขาดแบบตายตัว (ไม่ผ่าน AI) -----",
  "if (state.major === 'HR' && !infoComplete && !state.conversationEnded) {",
  "  const needsTrack = ['ปวส.','ปริญญาตรี'].includes(state.degree);",
  "  if (!state.degree) {",
  "    state.forcedAnswer = 'อาจารย์ขอสอบถามนะคะ นักศึกษาจบวุฒิใดและสาขาใดมาคะ';",
  "  } else if (needsTrack && !state.hrTrack) {",
  "    state.forcedAnswer = 'นักศึกษาจบสาขาใดมาคะ เช่น สายบริหารธุรกิจ สายสังคม หรือสายวิทยาศาสตร์ค่ะ';",
  "  } else if (!needsTrack && state.hrExperienceYears === null) {",
  "    state.forcedAnswer = 'นักศึกษามีประสบการณ์ทำงานมาแล้วกี่ปีคะ';",
  "  } else if (!state.govOrPrivate) {",
  "    state.forcedAnswer = 'ปัจจุบันนักศึกษาทำงานหน่วยงานรัฐหรือเอกชนคะ';",
  "  }",
  "}",
  "",
  "// ให้รายละเอียดคอร์ส HR (การจัดการทรัพยากรมนุษย์) แบบตายตัว จัดบรรทัดด้วยอีโมจิหมวด (สไตล์เดียวกับสาขาอื่น)",
  "if (state.major === 'HR' && infoComplete && !state.hrDetailGiven) {",
  "  const hrFee = state.govOrPrivate === 'รัฐ' ? '18,750 บาท/เทอม (มี 2 ทุนรวมกัน: ทุนลด 5,000 บาท และทุนลด 25% จากปกติ 30,000 บาท)' : '25,000 บาท/เทอม (มีทุนส่วนลด 5,000 บาท จากปกติ 30,000 บาท)';",
  "  let hrDuration, hrDurationKey;",
  "  if (['ปวส.','ปริญญาตรี'].includes(state.degree)) {",
  "    if (state.hrTrack === 'บริหารธุรกิจ') { hrDuration = '1.5 ปี'; hrDurationKey = '1.5y'; }",
  "    else if (state.hrTrack === 'สังคม') { hrDuration = '2 ปี'; hrDurationKey = '2y'; }",
  "    else { hrDuration = '2.5 ปี'; hrDurationKey = '2.5y'; }",
  "  } else if (state.govOrPrivate === 'รัฐ' && state.hrExperienceYears <= 11) {",
  "    // คนที่ทำงานรัฐ/รัฐวิสาหกิจอยู่แล้วถือว่ามีประสบการณ์ทำงานในตัวอยู่แล้ว ไม่มีเคส 0 ปีจริงๆ ปัดเข้ากลุ่ม 1-11 ปี (3 ปี) เสมอ",
  "    hrDuration = '3 ปี'; hrDurationKey = '3y';",
  "  } else {",
  "    if (state.hrExperienceYears === 0) { hrDuration = '3.5 ปี'; hrDurationKey = '3.5y'; }",
  "    else if (state.hrExperienceYears <= 11) { hrDuration = '3 ปี'; hrDurationKey = '3y'; }",
  "    else { hrDuration = '2.5 ปี'; hrDurationKey = '2.5y'; }",
  "  }",
  "  const HR_BASE = 'https://raw.githubusercontent.com/pakasit14-Sayfa/shinawatra-chatbot/main/backend-middleware/public/images/shinawatra/hr/';",
  "  const hrGovKey = state.govOrPrivate === 'รัฐ' ? 'gov' : 'private';",
  "  const hrImg = HR_BASE + 'hr-' + hrDurationKey + '-' + hrGovKey + '.jpg';",
  "  state.forcedAnswer = 'อาจารย์ขอสรุปรายละเอียดหลักสูตรการจัดการทรัพยากรมนุษย์ (HRM) ให้นะคะ\\n📍 รูปแบบเรียน: ออนไลน์วันอาทิตย์ (Block course)\\n🎓 เทียบโอน: ตามวุฒิและประสบการณ์ของนักศึกษา เหลือเรียนประมาณ ' + hrDuration + '\\n💰 ค่าเทอม: ' + hrFee + ' ผ่อนชำระรายเดือนได้\\n===\\n![ตารางค่าเทอมการจัดการทรัพยากรมนุษย์ ' + hrDuration + '](' + hrImg + ')\\n===\\nนักศึกษาสนใจสมัครเลยไหมคะ';",
  "  state.hrDetailGiven = true;",
  "}",
  "",
  "if (infoComplete) state.detailGiven = true;",
  "",
  "// ----- เช็คว่าข้อความนี้เป็นคำถามแทรกที่อยู่นอกขอบเขตงานคัดกรองหรือไม่ -----",
  "// ระบบนี้ทำหน้าที่แค่คัดกรองข้อมูลเบื้องต้น (เลือกสาขา + กรอกข้อมูลตามเกณฑ์) เท่านั้น",
  "// คำถามอื่นๆ (ค่าเทอม, ที่ตั้ง, กยศ., การรับรอง ฯลฯ) ให้ส่งต่อแอดมินจริงแทนการให้ AI เดาตอบ",
  "const fieldsAfter = JSON.stringify({major: state.major, degree: state.degree, grade: state.grade, track: state.track, age: state.age, weight: state.weight, height: state.height, govOrPrivate: state.govOrPrivate, pnTrack: state.pnTrack, engineeringType: state.engineeringType, isSpobTeacher: state.isSpobTeacher, eduHasLicense: state.eduHasLicense, hrTrack: state.hrTrack, hrExperienceYears: state.hrExperienceYears});",
  "const extractedSomethingNew = fieldsBefore !== fieldsAfter;",
  "const isGreetingOnly = /^(สวัสดี|หวัดดี|หัดดี|ดีครับ|ดีค่ะ|hi|hello)/.test(text.trim());",
  "const offTopic = !channelBlocked && !state.conversationEnded && !state.wantsAdmin && !extractedSomethingNew && !isGreetingOnly && hasQuestionMarker;",
  "// Whitelist: คำถามง่ายๆที่ปลอดภัยและมีคำตอบตายตัวชัดเจน ตอบตรงแทนการ deflect (เฉพาะเพจทั่วไป HR/วิศวะ/ป.โท/ป.บัณฑิต เท่านั้น ไม่แตะฝั่งพยาบาล)",
  "// อ้างอิงจากสไตล์การตอบจริงของแอดมิน (ตอบสั้นตรงประเด็นสำหรับคำถามง่ายๆ ไม่ deflect ทุกอย่าง)",
  "if (offTopic && !state.forcedAnswer && channel === 'general') {",
  "  if (/ยากไหม|ยากมั้ย|ยากป่าว|ยากหรือเปล่า|ยากรึเปล่า/.test(text)) {",
  "    state.forcedAnswer = 'ไม่ยากค่ะนักศึกษา';",
  "  } else if (/ออนไลน์ไหม|ออนไลน์มั้ย|ออนไลน์ใช่ไหม|ออนไลน์หรือเปล่า|ออนไลน์รึเปล่า/.test(text) && state.major) {",
  "    const onlineAnswer = {",
  "      EdAdminMaster: 'เรียนวันอาทิตย์ที่มหาวิทยาลัยชินวัตรค่ะ สามารถเรียนได้ทั้งรูปแบบ Online และ Onsite ค่ะ',",
  "      GradDip: 'เรียนออนไลน์เป็นหลักค่ะ วันเสาร์หรืออาทิตย์ตามอาจารย์ผู้สอน',",
  "      Engineering: 'เรียนออนไลน์+ออนไซต์ค่ะ วันธรรมดาภาคค่ำ 19:00-21:00 ไม่ทุกวัน และวันอาทิตย์เต็มวันออนไลน์ เข้ามหาวิทยาลัยน้อยมากค่ะ',",
  "      HR: 'เรียนออนไลน์วันอาทิตย์ค่ะ (Block course)'",
  "    }[state.major];",
  "    if (onlineAnswer) state.forcedAnswer = onlineAnswer;",
  "  } else if (/คุรุสภารับรอง|กคศ\\.?\\s*รับรอง|รับรองไหม|รับรองมั้ย/.test(text) && ['EdAdminMaster','GradDip'].includes(state.major)) {",
  "    state.forcedAnswer = 'หลักสูตรนี้คุรุสภารับรองเรียบร้อยแล้วค่ะ นักศึกษาสามารถตรวจสอบได้ด้วยตนเองที่ https://www.ksp.or.th/service/std.php ได้เลยนะคะ';",
  "  } else if (/มหาวิทยาลัยอยู่|อยู่ที่ไหน|อยู่ตรงไหน|อยู่จังหวัดไหน/.test(text)) {",
  "    state.forcedAnswer = 'มหาวิทยาลัยชินวัตร ตั้งอยู่ที่ อ.สามโคก จ.ปทุมธานีค่ะ';",
  "  } else if (/ต่างจังหวัด.*(ไหม|ได้)|ออนไซ|เข้ามหา(ลัย|วิทยาลัย).*บ่อย|ต้องเข้ามหา(ลัย|วิทยาลัย)/.test(text)) {",
  "    state.forcedAnswer = 'เรียนออนไลน์เป็นหลักค่ะ เข้ามหาวิทยาลัยน้อยมาก นักศึกษาส่วนใหญ่กว่า 80% อยู่ต่างจังหวัดค่ะ ไม่ต้องกังวลเลยนะคะ';",
  "  }",
  "}",
  "// คำถามแทรกนอกขอบเขตงานคัดกรอง (เช่น ถามเอกสารที่ต้องใช้, ค่าเทอม ฯลฯ) ที่ไม่เข้า whitelist ข้างบน ต้องตอบข้อความตายตัวเท่านั้น",
  "// ห้ามให้ AI พูดเอง เพราะ gpt-4o-mini มักไม่เชื่อฟังคำสั่ง \"ห้ามมั่ว\" แล้วมั่วรายละเอียด (เช่น รายการเอกสาร) ขึ้นมาเอง",
  "if (offTopic && !state.forcedAnswer) {",
  "  state.forcedAnswer = 'เดี๋ยวอาจารย์ติดต่อไปให้ข้อมูลเพิ่มเติมนะคะ';",
  "}",
  "",
  "return [{",
  "  json: {",
  "    ...state,",
  "    userId,",
  "    channel,",
  "    persona,",
  "    channelBlocked,",
  "    infoComplete,",
  "    rnEligible,",
  "    rnFailReasons,",
  "    pnEligible,",
  "    pnFailReasons,",
  "    offTopic,",
  "    multiProgramOptions: state.multiProgramOptions",
  "  }",
  "}];"
].join('\n');

const extractNode = wf.nodes.find(n => n.name === 'Extract Info (Deterministic)');
extractNode.parameters.jsCode = extractCode;

const promptParts = [
  "'คุณคือ \"' + $json.persona + '\" เจ้าหน้าที่ฝ่ายรับสมัคร มหาวิทยาลัยชินวัตร เรียกลูกค้าว่า \"' + ($json.channel === 'nursing' ? 'ลูก' : 'นักศึกษา') + '\" เสมอ (ห้ามใช้คำว่า ท่าน หรือ คุณ' + ($json.channel === 'nursing' ? ' หรือ นักศึกษา' : '') + ') พูดสุภาพ ลงท้ายด้วยค่ะ/นะคะเสมอ ห้ามใช้ครับ ตอบกระชับเป็นธรรมชาติ ห้ามพิมพ์ตัวเลข/ราคาที่ไม่ได้ให้มาในข้อมูลนี้เอง ห้ามมั่วข้อมูล ตัวเลขทุกตัว (ราคา, จำนวนปี, จำนวนที่นั่ง ฯลฯ) ต้องเขียนเป็นเลขอารบิกเสมอ (เช่น 150,000 บาท, 4 ปี) ห้ามสะกดเป็นคำอ่านภาษาไทยเด็ดขาด (ห้ามเขียนว่า หนึ่งแสนห้าหมื่นบาท หรือ สี่ปี) ห้ามใช้เครื่องหมาย ! (อัศเจรีย์) เด็ดขาดในทุกประโยค โดยเฉพาะประโยคชวนถามเพิ่มเติม ให้ลงท้ายด้วย \"นะคะ\" เสมอ ห้ามใช้ \"ค่ะ!\" ถ้าจะปิดท้ายด้วยการชวนถามเพิ่มเติม ให้ใช้ข้อความนี้เป๊ะๆเท่านั้น ห้ามแต่งเอง ห้ามชี้นำหัวข้อคำถาม: \"หากมีคำถามสอบถามเพิ่มเติมสามารถสอบถามอาจารย์ได้เลยนะคะ\". ทุกครั้งที่ต้องเสนอตัวเลือกหลายอย่างให้ลูกค้าเลือก (เช่น รายชื่อหลักสูตร, ประเภทภาคเรียน, รายการเงื่อนไข) ต้องจัดเป็นบรรทัดแยกแบบ bullet ขึ้นต้นด้วย \"- \" ทุกตัวเลือก ขึ้นบรรทัดใหม่จริง ห้ามเขียนตัวเลือกรวมในประโยคเดียวกันเด็ดขาด. ข้อมูลที่ต้องใช้ตอบ (ห้ามมั่ว ใช้ตามนี้เท่านั้น): ' + (function(){ ",
  "const j = $json; let facts = ''; ",
  "const FORM_NURSING = 'https://forms.gle/MKg5NfUtvjj1xr2k7'; ",
  "const FORM_ENGINEERING = 'https://forms.gle/nPJuM28hHuynxtp97'; ",
  "const FORM_HR = 'https://forms.gle/YBXny8GdW1VAXocJ6'; ",
  "const FORM_EDU = 'https://docs.google.com/forms/d/17Tq151nb8UH2C5QyL1EF922PzHrpGA_bCJhd7tnToLQ/viewform'; ",
  "if (j.channelBlocked) { facts = 'ลูกค้าถามเรื่องที่ช่องทางนี้ตอบไม่ได้ (เพจทั่วไปห้ามพูดพยาบาล หรือเพจพยาบาลห้ามพูดสาขาอื่น) ให้แนะนำไปเพจที่ถูกต้องอย่างสุภาพสั้นๆ ห้ามถามข้อมูลอะไรต่อ'; } ",
  "else if (j.offTopic) { facts = 'ลูกค้าถามคำถามที่อยู่นอกเหนือขอบเขตงานคัดกรองเบื้องต้น (ไม่ใช่การเลือกสาขาหรือให้ข้อมูลคัดกรอง) ห้ามพยายามตอบคำถามนั้นเองเด็ดขาด ห้ามมั่ว ให้ตอบสั้นๆ ว่าจะให้อาจารย์ติดต่อไปให้ข้อมูลเพิ่มเติมโดยตรง เช่น \"เดี๋ยวอาจารย์ติดต่อไปให้ข้อมูลเพิ่มเติมนะคะ\" ห้ามถามข้อมูลคัดกรองต่อในข้อความนี้'; } ",
  "else if (j.major === 'RN' && j.conversationEnded) { facts = 'ตอบเป๊ะๆ ห้ามแต่งเพิ่ม: \"หลักสูตรพยาบาล (RN) รับเฉพาะวุฒิ ม.6 สายสามัญเท่านั้นนะคะ วุฒิที่นักศึกษาแจ้งมายังไม่สามารถสมัครหลักสูตรนี้ได้ ต้องขออภัยด้วยนะคะ หากนักศึกษาสนใจหลักสูตรผู้ช่วยพยาบาล (PN) แทน สามารถแจ้งอาจารย์ได้เลยนะคะ\"'; } ",
  "else if (j.major === 'GradDip' && j.conversationEnded) { facts = 'ลูกค้าไม่ได้เป็นครูในโรงเรียนเครือ สพฐ. ซึ่งเป็นเงื่อนไขจำเป็นของหลักสูตร ป.บัณฑิต ให้แจ้งสุภาพว่าหลักสูตรนี้รับเฉพาะครูที่มีเอกสารรับรองการทำงานในโรงเรียนเครือ สพฐ. เท่านั้น ขออภัยในความไม่สะดวก'; } ",
  "else if (j.major === 'EdAdminMaster' && j.conversationEnded) { facts = 'ตอบเป๊ะๆ ห้ามแต่งเพิ่ม: \"ต้องขออภัยด้วยนะคะ หลักสูตร ป.โทบริหารการศึกษา จำเป็นจะต้องมีใบประกอบวิชาชีพครูก่อนค่ะนักศึกษา\"'; } ",
  "else if (j.wantsAdmin) { ",
  "  const formLink = ['RN','PN'].includes(j.major) ? FORM_NURSING : (j.major === 'Engineering' ? FORM_ENGINEERING : (j.major === 'HR' ? FORM_HR : (['EdAdminMaster','GradDip'].includes(j.major) ? FORM_EDU : null))); ",
  "  const QR_PAYMENT = 'https://raw.githubusercontent.com/pakasit14-Sayfa/shinawatra-chatbot/main/backend-middleware/public/images/shinawatra/payment-qr.png'; ",
  "  if (formLink) { facts = 'ลูกค้าสนใจสมัครแล้ว ตอบเป๊ะๆ คำต่อคำ ห้ามแต่งเพิ่ม ห้ามตัดคำ: อาจารย์ส่งแบบฟอร์มการกรอกข้อมูลการสมัครนะคะ\\n' + formLink + '\\n![QR ชำระเงิน](' + QR_PAYMENT + ')\\n===\\nลูกชำระค่าสมัครเรียบร้อยแล้วแจ้งอาจารย์นะคะ อาจารย์นำรายชื่อเข้าระบบให้ก่อนค่ะ ส่วนเอกสารที่ขาดสามารถแนบในฟอร์มภายหลังได้ค่ะลูก'; } ",
  "  else { facts = 'ลูกค้าตอบรับสนใจสมัครแล้วหลังจากได้รับรายละเอียดคอร์ส ให้ตอบรับสั้นๆ ว่าจะให้เจ้าหน้าที่ติดต่อนัดหมายต่อ แจ้งเบอร์ 082-383-0243 และ Line: @siu.admission'; } ",
  "} ",
  "else if (!j.major && j.channel === 'nursing') { facts = 'ยังไม่ทราบว่าลูกค้าสนใจหลักสูตรไหน ให้ตอบด้วยข้อความนี้เป๊ะๆ คำต่อคำตัวอักษรต่อตัวอักษร ห้ามแก้ไข ห้ามพูดถึง HR/วิศวะ/ป.โท/ป.บัณฑิตเด็ดขาด (เพจนี้มีแค่พยาบาลเท่านั้น) ต้องขึ้นบรรทัดใหม่ตรงตามนี้เป๊ะๆ: \"สวัสดีค่ะ ลูก\\nยินดีต้อนรับสู่มหาวิทยาลัยชินวัตรค่ะ สนใจหลักสูตรพยาบาลไหนคะ\\n- หลักสูตรพยาบาล (RN 4ปี)\\n- หลักสูตรผู้ช่วยพยาบาล (PN 1ปี)\\n(ภาคปกติ - ภาคพิเศษ)\\nสนใจหลักสูตรใดแจ้งอาจารย์ได้เลยนะคะ\"'; } ",
  "else if (!j.major) { facts = 'ยังไม่ทราบว่าลูกค้าสนใจสาขาไหน ให้ตอบด้วยข้อความนี้เป๊ะๆ คำต่อคำ ห้ามแก้ไข ห้ามพูดถึงพยาบาลหรือผู้ช่วยพยาบาลเด็ดขาด (เพจนี้ไม่มีหลักสูตรพยาบาล) ต้องขึ้นบรรทัดใหม่ตรงตามนี้เป๊ะๆ: \"สวัสดีค่ะ นักศึกษา\\nยินดีต้อนรับสู่มหาวิทยาลัยชินวัตรค่ะ สนใจหลักสูตรไหนคะ\\n- การจัดการทรัพยากรมนุษย์ (HR)\\n- วิศวกรรมศาสตร์\\n- ป.โทบริหารการศึกษา\\n- ป.บัณฑิตวิชาชีพครู\\nสนใจหลักสูตรใดแจ้งอาจารย์ได้เลยนะคะ\"'; } ",
  "else if (!j.infoComplete) { ",
  "  const noInfoYet = !j.degree && j.grade === null && !j.track && j.age === null && j.weight === null && j.height === null; ",
  "  const sixFieldTemplate = 'ตอบด้วยข้อความนี้เป๊ะๆ คำต่อคำ ห้ามแก้ไข ห้ามเพิ่มประโยคทักทายหรือประโยคย้ำว่านักศึกษาเลือกสาขาอะไร: \"อาจารย์ขอสอบถามข้อมูลเบื้องต้นของนักศึกษาก่อนนะคะ\\n- จบวุฒิการศึกษา =\\n- เกรดเฉลี่ย =\\n- สายการเรียน =\\n- อายุ =\\n- น้ำหนัก =\\n- ส่วนสูง =\\nนักศึกษาแจ้งข้อมูลข้างต้นเพื่อประเมินคุณสมบัติได้เลยนะคะ\"'; ",
  "  if (j.major === 'RN') { facts = noInfoYet ? sixFieldTemplate : ('สาขาที่ลูกค้าสนใจ: RN (พยาบาลศาสตร์). ข้อมูลที่มีแล้ว (ห้ามถามซ้ำ): วุฒิ=' + (j.degree||'-') + ' เกรด=' + (j.grade??'-') + ' สาย=' + (j.track||'-') + ' อายุ=' + (j.age??'-') + ' น้ำหนัก=' + (j.weight??'-') + ' ส่วนสูง=' + (j.height??'-') + '. ให้ถามเฉพาะข้อมูลที่ยังขาดจากรายการนี้เท่านั้น: วุฒิการศึกษา, เกรดเฉลี่ย, สายการเรียน, อายุ, น้ำหนัก(กก.), ส่วนสูง(ซม.)'); } ",
  "  else if (j.major === 'PN') { facts = sixFieldTemplate; } ",
  "  else if (j.major === 'Engineering') { facts = j.engineeringType ? ('สาขาที่ลูกค้าสนใจ: วิศวกรรมศาสตร์ หลักสูตร' + j.engineeringType + ' (เลือกหลักสูตรไว้แล้ว ห้ามถามหลักสูตรอื่นซ้ำเด็ดขาด ห้ามเสนอเครื่องกล/ความปลอดภัย/2ปริญญาอีก) ข้อมูลที่ยังขาด: วุฒิการศึกษา ให้ถามแค่วุฒิการศึกษาเท่านั้น') : 'สาขาที่ลูกค้าสนใจ: วิศวกรรมศาสตร์ ยังไม่ทราบว่าสนใจหลักสูตรใด ข้อมูลที่มีแล้ว (ห้ามถามซ้ำ): วุฒิ=' + (j.degree||'-') + '. ให้ถามเฉพาะข้อมูลที่ยังขาด: วุฒิการศึกษา (ถ้ายังไม่มี), และสนใจหลักสูตรเครื่องกล, ความปลอดภัย, หรือหลักสูตร 2 ปริญญา (วิศวกรรมเครื่องกลควบคู่วิศวกรรมความปลอดภัย)'; } ",
  "  else if (j.major === 'GradDip') { facts = 'สาขาที่ลูกค้าสนใจ: หลักสูตรประกาศนียบัตรบัณฑิตวิชาชีพครู (ป.บัณฑิต) ให้ถามว่านักศึกษาจบปริญญาตรีสาขาใดมา และปัจจุบันเป็นครูผู้สอนอยู่ที่โรงเรียนใด (รับทั้งโรงเรียนสพฐ.และเอกชนที่มีการเรียนการสอนปกติ เป็นเงื่อนไขจำเป็น ต้องมีเอกสารรับรองตำแหน่งครูผู้สอนชัดเจน)'; } ",
  "  else if (j.major === 'HR') { facts = 'สาขาที่ลูกค้าสนใจ: การจัดการทรัพยากรมนุษย์ (HR). ข้อมูลที่มีแล้ว (ห้ามถามซ้ำ): วุฒิ=' + (j.degree||'-') + ' หน่วยงาน=' + (j.govOrPrivate||'-') + '. ให้ถามเฉพาะข้อมูลที่ยังขาด: วุฒิการศึกษา และปัจจุบันทำงานหน่วยงานรัฐหรือเอกชน'; } ",
  "  else { facts = 'สาขาที่ลูกค้าสนใจ: ป.โทบริหารการศึกษา ให้ถามว่ามีใบประกอบวิชาชีพครูแล้วหรือยัง (เป็นเงื่อนไขจำเป็นเดียวของหลักสูตรนี้ ไม่ต้องถามวุฒิการศึกษา)'; } ",
  "} ",
  "else if (j.major === 'RN') { ",
  "  facts = j.rnEligible ",
  "    ? 'ลูกค้าผ่านเกณฑ์คุณสมบัติเบื้องต้นสำหรับ RN แล้ว ให้ตอบเป๊ะๆ คำต่อคำ ห้ามแต่งเพิ่ม ห้ามใส่รายละเอียดค่าเทอม/โควต้า/เงื่อนไขใดๆ เพิ่มเด็ดขาด ตอบเป็น 2 ข้อความแยกกันด้วย === แบบนี้: \"คุณสมบัติเบื้องต้นของลูกผ่านเกณฑ์นะคะ อาจารยส่งรายละเอียดให้ค่ะ === ![ตารางผ่อนชำระกรณีกู้ กยศ.](https://raw.githubusercontent.com/pakasit14-Sayfa/shinawatra-chatbot/main/backend-middleware/public/images/shinawatra/nursing/rn-loan-installment-table.jpg)\"' ",
  "    : 'ลูกค้าไม่ผ่านเกณฑ์ RN เนื่องจาก: ' + j.rnFailReasons.join(', ') + ' ให้แจ้งสุภาพว่าไม่ผ่านเกณฑ์ข้อไหน และแนะนำพิจารณาหลักสูตรผู้ช่วยพยาบาล (PN) แทน'; ",
  "} ",
  "else if (j.major === 'PN' && !j.pnEligible) { facts = 'ลูกค้าไม่ผ่านเกณฑ์ PN เนื่องจาก: ' + j.pnFailReasons.join(', ') + ' ให้แจ้งสุภาพว่าไม่ผ่านเกณฑ์ข้อไหน'; } ",
  "else if (j.major === 'PN' && !j.pnTrack) { facts = 'ลูกให้ข้อมูลครบแล้ว แต่ยังไม่ทราบว่าต้องการเรียนภาคไหน ให้ตอบสั้นๆ ว่าคุณสมบัติเบื้องต้นผ่านแล้ว แล้วถามว่าต้องการเรียนภาคปกติ (จันทร์-ศุกร์ ที่ปทุมธานี) หรือภาคพิเศษ (เสาร์-อาทิตย์ ที่อโศก)'; } ",
  "else if (j.major === 'PN') { ",
  "  const locationLine = j.pnTrack === 'พิเศษ' ? 'เรียนที่อาคาร OAI ย่านอโศก กรุงเทพมหานคร (เข้าแลบ/ฝึกงานต้องไปปทุมธานี)' : 'เรียนที่มหาวิทยาลัยชินวัตร จังหวัดปทุมธานี'; ",
  "  facts = 'PN (ผู้ช่วยพยาบาล 1 ปี ภาค' + j.pnTrack + ' ' + locationLine + ') ค่าสมัคร 500 บาท ภาคเรียนที่ 1 มีค่าใช้จ่ายส่วนต่าง 31,000 บาท (รวมค่าสมัครแล้ว) แบ่งชำระได้ ภาคเรียนที่ 2-3 สำรองชำระล่วงหน้า 50,000 บาท กู้ กยศ.ได้สูงสุด 50,000 บาทตลอดหลักสูตร (อนุมัติตามเงื่อนไข กยศ.) ให้สรุปข้อมูลคอร์สแล้วถามว่าสนใจสมัครเลยไหมคะ'; ",
  "} ",
  "else if (j.major === 'HR') { ",
  "  const fee = j.govOrPrivate === 'รัฐ' ? '18,750 บาท/เทอม (มี 2 ทุนรวมกัน: ทุนลด 5,000 บาท และทุนลด 25% จากปกติ 30,000 บาท)' : '25,000 บาท/เทอม (มีทุนส่วนลด 5,000 บาท จากปกติ 30,000 บาท)'; ",
  "  facts = 'HRM การจัดการทรัพยากรมนุษย์ (เรียนออนไลน์วันอาทิตย์ Block course, เทียบโอนได้ สายบริหารธุรกิจเหลือเรียนประมาณ 1.5 ปี) ลูกค้าทำงาน ' + j.govOrPrivate + ' ค่าเทอม ' + fee + ' ผ่อนชำระรายเดือนได้ ให้สรุปแล้วถามว่าสนใจสมัครเลยไหมคะ'; ",
  "} ",
  "else if (j.major === 'Engineering') { ",
  "  const isTransfer = ['ปวส.','ปริญญาตรี'].includes(j.degree); ",
  "  let detail = ''; ",
  "  if (j.engineeringType === 'เครื่องกล') detail = isTransfer ? 'เทียบโอนเหลือเรียน 2 ปี ค่าเทอมเหมา 150,000 บาท' : 'เรียนเต็ม 4 ปี ค่าเทอม 280,000 บาท'; ",
  "  else if (j.engineeringType === 'ความปลอดภัย') detail = isTransfer ? 'เทียบโอนเหลือเรียน 2 ปี ค่าเทอมเหมา 150,000 บาท' : 'เรียนเต็ม 4 ปี ค่าเทอม 280,000 บาท'; ",
  "  else detail = isTransfer ? 'เทียบโอนเหลือเรียน 3 ปี ค่าเทอมตลอดหลักสูตร 255,000 บาท' : 'เรียนเต็ม 4 ปี ค่าเทอมตลอดหลักสูตร 320,000 บาท'; ",
  "  facts = 'วิศวกรรมศาสตร์ หลักสูตร' + j.engineeringType + ' (เรียนออนไลน์+ออนไซต์ วันธรรมดาภาคค่ำ 19:00-21:00 ไม่ทุกวัน + วันอาทิตย์เต็มวันออนไลน์ เข้ามหาวิทยาลัยน้อยมาก) วุฒิลูกค้า=' + j.degree + ' ' + detail + '. เครื่องกลรับรองจากสภาวิศวกร ได้สิทธิ์สอบ กว. / ความปลอดภัยรับรองจากกรมสวัสดิการและคุ้มครองแรงงาน ได้ใบประกอบวิชาชีพ จป.เลยไม่ต้องสอบเพิ่ม ให้สรุปแล้วถามว่าสนใจสมัครเลยไหมคะ'; ",
  "} ",
  "else if (j.major === 'EdAdminMaster') { facts = 'ป.โทบริหารการศึกษา (เรียนวันอาทิตย์ 2 ปี, ค่าเทอม 150,000 บาท แบ่ง 7 งวด, ค่าสมัคร 1,500 บาท, ต้องมีใบประกอบวิชาชีพครู, หลักสูตรคุรุสภารับรอง, เมื่อเรียนจบสามารถนำวุฒิยื่นขอใบประกอบวิชาชีพผู้บริหารสถานศึกษาได้เลยไม่ต้องสอบเพิ่มเติม) ให้สรุปแล้วถามว่ามีใบประกอบวิชาชีพครูหรือยัง และถามว่าสนใจสมัครเลยไหมคะ'; } ",
  "else if (j.major === 'GradDip') { facts = 'ป.บัณฑิตวิชาชีพครู (ลูกค้าเป็นครูเครือ สพฐ. ผ่านเงื่อนไขแล้ว) เรียนออนไลน์เป็นหลัก วันเสาร์หรืออาทิตย์ขึ้นกับอาจารย์ผู้สอน เปิดภาคเรียนเดือนธันวาคม 2569 ค่าสมัคร 1,500 บาท ค่าเทอมตลอดหลักสูตร 54,000 บาท ผ่อนชำระรายเดือนได้ ระยะเวลา 1.5 ปี (3 เทอม) เข้าร่วมกิจกรรมที่มหาวิทยาลัยเทอมละ 1 ครั้ง (รวม 3 ครั้งตลอดหลักสูตร) หลักสูตรคุรุสภารับรอง เมื่อเรียนจบมีสิทธิ์สอบใบประกอบวิชาชีพครู ให้สรุปแล้วถามว่าสนใจสมัครเลยไหมคะ'; } ",
  "return facts; })()"
];
const promptExpr = promptParts.join('');

const jsonBodyValue = "={{ JSON.stringify({ model: 'gpt-4o-mini', temperature: 0.5, messages: [ { role: 'system', content: " + promptExpr + " }, ...$json.history ] }) }}";

const aiNode = wf.nodes.find(n => n.name === 'AI - Generate Reply');
aiNode.parameters.jsonBody = jsonBodyValue;

const mergeNode = wf.nodes.find(n => n.name === 'Merge Answer');
mergeNode.parameters.jsCode = [
  "const incoming = $input.first().json;",
  "const state = $('Extract Info (Deterministic)').first().json;",
  "// ถ้า Extract Info กำหนดคำตอบตายตัวไว้แล้ว (เช่น ข้อความส่งฟอร์ม+QR) ให้ใช้ตรงนั้นเลย ไม่ใช้คำตอบจาก AI",
  "// เพราะ gpt-4o-mini มักแก้คำ/ลืมรายละเอียดเมื่อข้อความมีหลายส่วนประกอบ (ลิงก์+รูป+คำเรียกเฉพาะ)",
  "const answer = state.forcedAnswer || incoming.choices[0].message.content;",
  "state.history.push({ role: 'assistant', content: answer });",
  "return [{ json: { ...state, answer } }];"
].join('\n');

const saveNode = wf.nodes.find(n => n.name === 'Redis Save State');
saveNode.parameters.value = "={{ JSON.stringify({history: $json.history, major: $json.major, degree: $json.degree, job: $json.job, experience: $json.experience, grade: $json.grade, track: $json.track, age: $json.age, weight: $json.weight, height: $json.height, govOrPrivate: $json.govOrPrivate, pnTrack: $json.pnTrack, engineeringType: $json.engineeringType, isSpobTeacher: $json.isSpobTeacher, eduHasLicense: $json.eduHasLicense, hrTrack: $json.hrTrack, hrExperienceYears: $json.hrExperienceYears, conversationEnded: $json.conversationEnded, detailGiven: $json.detailGiven, pnDetailGiven: $json.pnDetailGiven, eduDetailGiven: $json.eduDetailGiven, gradDipDetailGiven: $json.gradDipDetailGiven, engineeringDetailGiven: $json.engineeringDetailGiven, hrDetailGiven: $json.hrDetailGiven}) }}";

const payload = { name: wf.name, nodes: wf.nodes, connections: wf.connections, settings: {} };
fs.writeFileSync('brain2_updated.json', JSON.stringify(payload));
console.log('hasNewlineInJsonBody:', /[\r\n]/.test(jsonBodyValue));
console.log('done, nodes count:', wf.nodes.length, 'jsonBody length:', jsonBodyValue.length);
