const fs = require('fs');
const wf = JSON.parse(fs.readFileSync('brain3_current.json', 'utf8'));

const extractCode = [
  "let state;",
  "try { state = JSON.parse($input.first().json.stateRaw || '{}'); } catch (e) { state = {}; }",
  "state.history = state.history || [];",
  "state.age = state.age ?? null;",
  "state.hasBasic = state.hasBasic ?? null; // true/false มีพื้นฐานภาษาจีนหรือไม่",
  "state.beenChina = state.beenChina ?? null; // true/false เคยไปเรียนที่จีนมาก่อนไหม",
  "state.city = state.city || null; // Guangzhou, Shanghai, Weihai, Harbin",
  "state.university = state.university || null; // SCNU, GTC (เฉพาะกว่างโจว) ส่วนเมืองอื่น auto-set ตามเมือง",
  "state.duration = state.duration || null; // '1term', '1term_intensive', '1year'",
  "state.shanghaiTrack = state.shanghaiTrack || null; // 'standard', 'intensive', 'business' (เฉพาะเซี่ยงไฮ้)",
  "state.ageRejected = state.ageRejected || false;",
  "state.detailGiven = state.detailGiven || false;",
  "state.wantsAdmin = false;",
  "",
  "const webhookBody = $('Webhook').first().json.body;",
  "const userId = webhookBody.userId;",
  "// pageType: 'guangzhou' | 'shanghai' | 'weihai' | 'harbin' | 'china_all' | 'combined' (เพจรวม/LINE)",
  "const pageType = webhookBody.pageType || 'china_all';",
  "const rawMessage = webhookBody.message || '';",
  "state.history.push({ role: 'user', content: rawMessage });",
  "const text = rawMessage.toLowerCase();",
  "const numbers = (rawMessage.match(/\\d+/g) || []).map(Number);",
  "",
  "// ----- บีบเมืองตาม pageType ถ้าเป็นเพจเฉพาะเมือง (เพจรวม/LINE ค่อยถามทีหลัง) -----",
  "const CITY_BY_PAGE = { guangzhou: 'Guangzhou', shanghai: 'Shanghai', weihai: 'Weihai', harbin: 'Harbin' };",
  "if (CITY_BY_PAGE[pageType]) state.city = CITY_BY_PAGE[pageType];",
  "",
  "// ----- ตรวจคำตอบรับสั้นๆ หลังให้รายละเอียดคอร์สไปแล้ว -----",
  "const confirmWords = ['สนใจ', 'ใช่', 'ตกลง', 'โอเค', 'เอาเลย', 'อยากสมัคร', 'สมัคร'];",
  "if (state.detailGiven && confirmWords.some(w => text.includes(w))) {",
  "  state.wantsAdmin = true;",
  "}",
  "",
  "// ----- ดึงอายุ/พื้นฐานภาษา/ประวัติเคยไปจีน (deterministic) -----",
  "if (state.age === null) {",
  "  const ageNear = text.match(/อายุ\\D{0,5}(\\d{1,3})/);",
  "  if (ageNear && Number(ageNear[1]) >= 5 && Number(ageNear[1]) <= 80) state.age = Number(ageNear[1]);",
  "  else { const a = numbers.find(n => n >= 10 && n <= 80); if (a !== undefined) state.age = a; }",
  "}",
  "if (state.hasBasic === null) {",
  "  if (/ไม่มีพื้นฐาน|ไม่มี basic|ไม่เคยเรียน|ไม่เป็นเลย/.test(text)) state.hasBasic = false;",
  "  else if (/มีพื้นฐาน|พอได้บ้าง|hsk/.test(text)) state.hasBasic = true;",
  "}",
  "if (state.beenChina === null) {",
  "  if (/ไม่เคยไปจีน|ไม่เคยไป/.test(text)) state.beenChina = false;",
  "  else if (/เคยไปจีน|เคยไป/.test(text)) state.beenChina = true;",
  "}",
  "",
  "// ----- ดึงชื่อเมือง (เฉพาะกรณีเพจรวม/LINE ที่ยังไม่ถูกบีบเมือง) -----",
  "if (!state.city) {",
  "  if (text.includes('กว่างโจว')) state.city = 'Guangzhou';",
  "  else if (text.includes('เซี่ยงไฮ้')) state.city = 'Shanghai';",
  "  else if (text.includes('เวยไห่')) state.city = 'Weihai';",
  "  else if (text.includes('ฮาร์บิน')) state.city = 'Harbin';",
  "}",
  "",
  "// ----- กว่างโจว: เลือกมหาวิทยาลัย SCNU หรือ GTC -----",
  "if (state.city === 'Guangzhou' && !state.university) {",
  "  if (/scnu/.test(text)) state.university = 'SCNU';",
  "  else if (/gtc/.test(text)) state.university = 'GTC';",
  "}",
  "if (state.city && state.city !== 'Guangzhou' && !state.university) {",
  "  state.university = { Shanghai: 'ECUST', Weihai: 'SDUW', Harbin: 'HEU' }[state.city];",
  "}",
  "",
  "// ----- เช็คเกณฑ์อายุตามมหาวิทยาลัยที่เลือก (deterministic ตามเอกสารจริง) -----",
  "const AGE_RANGE = { SCNU: [18, 40], GTC: [18, 35], ECUST: [18, 45], SDUW: [18, 60], HEU: [18, 45] };",
  "if (state.university && state.age !== null && !state.ageRejected && !state.duration) {",
  "  const range = AGE_RANGE[state.university];",
  "  if (range && (state.age < range[0] || state.age > range[1])) {",
  "    state.ageRejected = true;",
  "  }",
  "}",
  "",
  "// ----- เซี่ยงไฮ้: เลือกหลักสูตรย่อยตาม HSK (Standard/Intensive/Business) -----",
  "if (state.city === 'Shanghai' && !state.shanghaiTrack) {",
  "  if (/ธุรกิจ|business/.test(text)) state.shanghaiTrack = 'business';",
  "  else if (/เร่งรัด|intensive/.test(text)) state.shanghaiTrack = 'intensive';",
  "  else if (/ปกติ|standard/.test(text)) state.shanghaiTrack = 'standard';",
  "}",
  "",
  "// ----- เลือกระยะเวลาคอร์ส -----",
  "if (!state.duration) {",
  "  const saysIntensive = /เร่งรัด|intensive/.test(text);",
  "  const saysYear = /1\\s*ปี|หนึ่งปี/.test(text);",
  "  const saysTerm = /1\\s*เทอม|หนึ่งเทอม/.test(text);",
  "  if (state.university === 'SCNU' && saysIntensive) state.duration = '1term_intensive';",
  "  else if (saysYear) state.duration = '1year';",
  "  else if (saysTerm) state.duration = '1term';",
  "}",
  "",
  "const infoComplete = state.age !== null && state.hasBasic !== null && state.beenChina !== null;",
  "const detailReady = infoComplete && state.city && state.university && !state.ageRejected",
  "  && state.duration && (state.city !== 'Shanghai' || state.shanghaiTrack);",
  "if (detailReady) state.detailGiven = true;",
  "",
  "return [{ json: { ...state, userId, pageType, infoComplete, detailReady } }];"
].join('\n');

// ===== ข้อมูลค่าใช้จ่ายจริงต่อมหาวิทยาลัย/ระยะเวลา (อ้างอิงเอกสาร 01-04 + General_Information ปี 2569) =====
// ทุกตัวเลขเป็น forcedAnswer ตายตัว ห้ามให้ AI พูดเอง กันมั่วราคา (root cause ของบั๊กเดิม)
const forcedAnswerCode = [
  "// ----- คำนวณ forcedAnswer แบบตายตัว ไม่ผ่าน AI เด็ดขาดสำหรับเรื่องราคา/เกณฑ์ -----",
  "let forcedAnswer = null;",
  "",
  "if (state.wantsAdmin) {",
  "  forcedAnswer = 'ขอบคุณที่สนใจสมัครเรียนนะคะ เดี๋ยวพี่จะให้เจ้าหน้าที่ Dilion Education ติดต่อกลับไปดูแลเรื่องเอกสาร/ฟอร์มสมัครให้นะคะ';",
  "} else if (!infoComplete) {",
  "  const need = [];",
  "  if (state.age === null) need.push('อายุเท่าไหร่');",
  "  if (state.hasBasic === null) need.push('มีพื้นฐานภาษาจีนหรือไม่');",
  "  if (state.beenChina === null) need.push('เคยไปเรียนที่ประเทศจีนมาก่อนไหม');",
  "  forcedAnswer = 'ขออนุญาตสอบถามข้อมูลของน้องๆเพิ่มเติมนะคะ\\n- ' + need.join('\\n- ');",
  "} else if (!state.city) {",
  "  forcedAnswer = 'ตอนนี้พี่ๆทำความร่วมมือกับเมืองดังนี้ค่ะ\\n- กว่างโจว\\n- เซี่ยงไฮ้\\n- เวยไห่\\n- ฮาร์บิน\\nสนใจเรียนเมืองไหนดีคะ';",
  "} else if (state.city === 'Guangzhou' && !state.university) {",
  "  forcedAnswer = 'ที่กว่างโจวมี 2 สถาบันให้เลือกค่ะ\\n- SCNU (South China Normal University) เหมาะกับผู้ที่อยากต่อยอดเรียน/สมัครงาน รับอายุ 18-40 ปี\\n- GTC (Guangdong Teachers College) เน้นพูดได้ไว ได้วีซ่า X1 ทุกระยะเวลา รับอายุ 18-35 ปี\\nสนใจที่ไหนคะ';",
  "} else if (state.ageRejected) {",
  "  const range = { SCNU: '18-40', GTC: '18-35', ECUST: '18-45', SDUW: '18-60', HEU: '18-45' }[state.university];",
  "  forcedAnswer = 'เกณฑ์การรับสมัครของ ' + state.university + ' จะรับอายุ ' + range + ' ปีค่ะ น้องสนใจเป็นเมือง/สถาบันอื่นไหมคะ เดี๋ยวพี่ส่งต่อให้แอดมินช่วยดูแลต่อนะคะ';",
  "} else if (state.city === 'Shanghai' && !state.shanghaiTrack) {",
  "  forcedAnswer = 'ที่ ECUST เซี่ยงไฮ้มี 3 คอร์สให้เลือกค่ะ\\n- Standard Chinese: ไม่ต้องมีพื้นฐาน ไม่ต้องใช้ HSK\\n- Intensive Chinese: ต้องมี HSK3 ขึ้นไป\\n- Business Chinese: ต้องมี HSK4 ขึ้นไป\\nสนใจคอร์สไหนคะ';",
  "} else if (state.city === 'Shanghai' && state.shanghaiTrack !== 'standard' && !state.hasBasic) {",
  "  forcedAnswer = 'คอร์สนี้ต้องใช้ผลสอบ HSK ในการสมัครด้วยค่ะ น้องสนใจเป็นคอร์ส Standard Chinese ไหมคะ ไม่ต้องใช้ผลสอบ HSK ไม่มีพื้นฐานก็เรียนได้ค่ะ';",
  "} else if (!state.duration) {",
  "  if (state.university === 'SCNU') forcedAnswer = 'ตอนนี้ทางเรามีคอร์สให้เลือกค่ะ\\n- 1 เทอมปกติ (เรียนเช้า จันทร์-ศุกร์)\\n- 1 เทอมเร่งรัด (เรียนเช้า-บ่าย ได้ผลเทียบเท่า 1 ปีใน 1 เทอม)\\n- 1 ปี (รวม 2 เทอม)\\nสนใจคอร์สไหนคะ';",
  "  else forcedAnswer = 'สนใจคอร์ส 1 เทอม หรือ 1 ปีคะ';",
  "} else {",
  "  // ครบข้อมูลแล้ว -> สรุปรายละเอียด+ราคาแบบตายตัว",
  "  const FACTS = {",
  "    SCNU: {",
  "      '1term': { rmb: '13,800-15,700', thb: '62,790-71,435', months: '4 เดือนครึ่ง', visa: 'X2 (ออกนอกจีนกลางเทอมไม่ได้)', dorm: 'ไม่มีหอใน (ปิดปรับปรุง) หอนอก 2,800-3,500 หยวน/เดือน' },",
  "      '1term_intensive': { rmb: '21,700-23,600', thb: '98,735-107,380', months: '4 เดือนครึ่ง (เทียบเท่าหลักสูตร 1 ปี)', visa: 'X2 (ออกนอกจีนกลางเทอมไม่ได้)', dorm: 'ไม่มีหอใน (ปิดปรับปรุง) หอนอก 2,800-3,500 หยวน/เดือน' },",
  "      '1year': { rmb: '23,400-25,750', thb: '106,470-117,163', months: '12 เดือน (2 เทอม)', visa: 'X1 (ยื่น Resident Permit ได้)', dorm: 'ไม่มีหอใน (ปิดปรับปรุง) หอนอก 2,800-3,500 หยวน/เดือน' },",
  "    },",
  "    GTC: {",
  "      '1term': { rmb: '12,300-13,350', thb: '55,965-60,743', months: '4 เดือนครึ่ง', visa: 'X1 (ยื่น Resident Permit ได้)', dorm: 'หอในห้องคู่ (พักกับเพื่อนไทยเพศเดียวกัน)' },",
  "      '1year': { rmb: '20,200-21,250', thb: '91,910-96,688', months: '12 เดือน (2 เทอม)', visa: 'X1 (ยื่น Resident Permit ได้)', dorm: 'หอในห้องคู่ (พักกับเพื่อนไทยเพศเดียวกัน)' },",
  "    },",
  "    SDUW: {",
  "      '1term': { rmb: '11,560-12,550', thb: '52,598-57,102', months: '4 เดือนครึ่ง', visa: 'X2 (ออกนอกจีนกลางเทอมไม่ได้)', dorm: 'หอในมหาวิทยาลัยให้บริการ' },",
  "      '1year': { rmb: '24,420-25,410', thb: '111,111-115,615', months: '12 เดือน (2 เทอม)', visa: 'X1 (ยื่น Resident Permit ได้)', dorm: 'หอในมหาวิทยาลัยให้บริการ' },",
  "    },",
  "    HEU: {",
  "      '1term': { rmb: '9,600-10,800', thb: '43,680-49,140', months: '4 เดือนครึ่ง', visa: 'X2 (ออกนอกจีนกลางเทอมไม่ได้)', dorm: 'หอในห้องคู่ (พักกับเพื่อนไทยเพศเดียวกัน)' },",
  "      '1year': { rmb: '18,500-19,750', thb: '84,175-89,863', months: '12 เดือน (2 เทอม)', visa: 'X1 (ยื่น Resident Permit ได้)', dorm: 'หอในห้องคู่ (พักกับเพื่อนไทยเพศเดียวกัน)' },",
  "    },",
  "    ECUST: {",
  "      standard: { rmb: '20,000-22,400', thb: '91,000-101,920', months: '4 เดือนครึ่ง', visa: 'X2 (ออกนอกจีนกลางเทอมไม่ได้)', dorm: 'ปกติหอในห้องเดี่ยว (เทอมก.ย.69 อาจแน่น ให้สิทธิ์ปี/โท/เอกก่อน)' },",
  "      intensive: { rmb: '24,200-26,600', thb: '110,110-121,030', months: '4 เดือนครึ่ง', visa: 'X2 (ออกนอกจีนกลางเทอมไม่ได้)', dorm: 'ปกติหอในห้องเดี่ยว (เทอมก.ย.69 อาจแน่น ให้สิทธิ์ปี/โท/เอกก่อน)' },",
  "      business: { rmb: '21,200-23,600', thb: '96,460-107,380', months: '4 เดือนครึ่ง', visa: 'X2 (ออกนอกจีนกลางเทอมไม่ได้)', dorm: 'ปกติหอในห้องเดี่ยว (เทอมก.ย.69 อาจแน่น ให้สิทธิ์ปี/โท/เอกก่อน)' },",
  "    },",
  "  };",
  "  const UNI_NAME = { SCNU: 'South China Normal University (SCNU) กว่างโจว', GTC: 'Guangdong Teachers College (GTC) กว่างโจว', ECUST: 'East China University of Science and Technology (ECUST) เซี่ยงไฮ้', SDUW: 'Shandong University, Weihai Campus (SDUW) เวยไห่', HEU: 'Harbin Engineering University (HEU) ฮาร์บิน' };",
  "  const key = state.city === 'Shanghai' ? state.shanghaiTrack : state.duration;",
  "  const f = FACTS[state.university][key];",
  "  const durationLabel = state.city === 'Shanghai' ? { standard: 'Standard Chinese (1 เทอม)', intensive: 'Intensive Chinese (1 เทอม)', business: 'Business Chinese (1 เทอม)' }[key] : { '1term': '1 เทอม', '1term_intensive': '1 เทอมเร่งรัด', '1year': '1 ปี' }[key];",
  "  const PAY_FIRST = { SCNU: '14,500', GTC: '15,000', ECUST: '14,400', SDUW: '14,500', HEU: '14,500' }[state.university];",
  "  forcedAnswer = 'รายละเอียดคอร์ส ' + durationLabel + ' ที่ ' + UNI_NAME[state.university] + ' ค่ะ\\n' +",
  "    '🗓 ระยะเวลาเรียน: ' + f.months + '\\n' +",
  "    '💰 ค่าใช้จ่ายฝั่งจีน (ค่าเรียน+ธรรมเนียม+หอพัก โดยประมาณ): ' + f.rmb + ' หยวน (≈' + f.thb + ' บาท)\\n' +",
  "    '💳 ชำระยอดแรกฝั่งไทย: ' + PAY_FIRST + ' บาท (รวมค่าสมัคร+เอกสารจากจีน+วีซ่านักเรียน+รับที่สนามบิน) ส่วนที่เหลือชำระตรงกับมหาวิทยาลัยที่จีนค่ะ\\n' +",
  "    '🛏 ที่พัก: ' + f.dorm + '\\n' +",
  "    '🛂 วีซ่า: ' + f.visa + '\\n' +",
  "    '(ราคาเป็นตัวอย่างปี 2569 อาจมีการปรับเปลี่ยนตามประกาศจริงของมหาวิทยาลัย)\\n' +",
  "    'น้องอ่านรายละเอียดก่อนได้เลยนะคะ สนใจสมัครแจ้งพี่ได้เลยค่ะ';",
  "}",
  "",
  "state.forcedAnswer = forcedAnswer;"
].join('\n');

const extractNode = wf.nodes.find(n => n.name === 'Extract Info (Deterministic)');
extractNode.parameters.jsCode = extractCode.replace(
  "return [{ json: { ...state, userId, pageType, infoComplete, detailReady } }];",
  ""
) + '\n' + forcedAnswerCode + '\nreturn [{ json: { ...state, userId, pageType, infoComplete, detailReady } }];';

// ===== Merge Answer: ใช้ forcedAnswer ตรงๆ ถ้ามี ไม่ผ่าน AI เพื่อกันมั่วราคา =====
const mergeNode = wf.nodes.find(n => n.name === 'Merge Answer');
mergeNode.parameters.jsCode = [
  "const incoming = $input.first().json;",
  "const state = $('Extract Info (Deterministic)').first().json;",
  "const answer = state.forcedAnswer || incoming.choices[0].message.content;",
  "state.history.push({ role: 'assistant', content: answer });",
  "return [{ json: { ...state, answer } }];"
].join('\n');

// ===== AI node: ใช้แค่ตอบคำถามแทรกทั่วไปที่ไม่เกี่ยวราคา/เกณฑ์ (กรณี forcedAnswer ไม่ตรงเคสไหนเลย) =====
const aiNode = wf.nodes.find(n => n.name === 'AI - Generate Reply');
const KB_GENERAL = [
  "Q: เรียนเมืองอื่น/ม.อื่นได้ไหม (เฉิงตู ปักกิ่ง ฯลฯ) A: ทางเราทำความร่วมมือเฉพาะ 4 เมืองนี้ค่ะ กว่างโจว เซี่ยงไฮ้ เวยไห่ ฮาร์บิน",
  "Q: มีคอร์สระยะสั้น 1 เดือน/2 สัปดาห์ไหม A: ตอนนี้ยังไม่เปิดรับ มีแพลนเปิดอีกครั้งช่วงเดือนตุลาคม รอติดตามที่หน้าเพจได้เลยค่ะ",
  "Q: มีทุนไหม A: ทุนจะเข้ามาช่วงต้นปี และต้องมีผลสอบ HSK กับ HSKK ในระดับที่ปลอดภัยสำหรับยื่นขอทุนค่ะ",
  "Q: มีคอร์สมัธยม/ม.ปลายไหม A: ยังไม่มีค่ะ มีแค่คอร์สเรียนภาษา 1 เทอมและ 1 ปีค่ะ",
  "Q: เปิดเรียนกี่รอบต่อปี A: เปิด 2 รอบค่ะ เทอมกันยายน (ก.ย.-ม.ค.) และเทอมมีนาคม (มี.ค.-ก.ค.)"
].join(' | ');
aiNode.parameters.jsonBody = "={{ JSON.stringify({\n  model: 'gpt-4o-mini',\n  temperature: 0.3,\n  messages: [\n    { role: 'system', content: 'คุณคือเจ้าหน้าที่ Dilion Education ศูนย์แนะนำเรียนต่อประเทศจีน พูดสุภาพ ลงท้าย \"ค่ะ\" เสมอ ห้ามใช้ \"ครับ\" กระชับเป็นธรรมชาติ ห้ามมั่วราคา/เงื่อนไขที่ไม่ได้ให้มาในฐานความรู้นี้เด็ดขาด ถ้าไม่มีข้อมูลให้ตอบว่าจะให้เจ้าหน้าที่ติดต่อไปให้ข้อมูลเพิ่มเติม ฐานความรู้: " + KB_GENERAL + "' },\n    ...$json.history\n  ]\n}) }}";

wf.connections = {
  'Webhook': { main: [[{ node: 'Redis Get State', type: 'main', index: 0 }]] },
  'Redis Get State': { main: [[{ node: 'Extract Info (Deterministic)', type: 'main', index: 0 }]] },
  'Extract Info (Deterministic)': { main: [[{ node: 'AI - Generate Reply', type: 'main', index: 0 }]] },
  'AI - Generate Reply': { main: [[{ node: 'Merge Answer', type: 'main', index: 0 }]] },
  'Merge Answer': { main: [[{ node: 'Redis Save State', type: 'main', index: 0 }]] },
  'Redis Save State': { main: [[{ node: 'Respond to Webhook', type: 'main', index: 0 }]] }
};

const saveNode = wf.nodes.find(n => n.name === 'Redis Save State');
saveNode.parameters.value = "={{ JSON.stringify({history: $json.history, age: $json.age, hasBasic: $json.hasBasic, beenChina: $json.beenChina, city: $json.city, university: $json.university, duration: $json.duration, shanghaiTrack: $json.shanghaiTrack, ageRejected: $json.ageRejected, detailGiven: $json.detailGiven}) }}";

const payload = { name: wf.name, nodes: wf.nodes, connections: wf.connections, settings: wf.settings || {} };
fs.writeFileSync('brain3_updated.json', JSON.stringify(payload));
console.log('done, nodes count:', wf.nodes.length);
